#!/usr/bin/env python3
"""Generate one section's .tex from the section Page that authors it.

🚫 FABRICATED content. See `QBt6-for-section.md`.

WHY THIS SCRIPT IS SHARED. A display unit's build is per unit: one
`displays/<page>/source/build.py` renders one figure. A section's is not. On a
real paper every section .tex comes out of ONE engine, `stage.py sync`, and
`S06-main/section-edit/stage.md` says so in one line:

    output: sections/*.tex   # GENERATED from the .md by sync; NEVER hand-authored

So this file is the group's whole section sync, not `QBt6`'s recipe. Add a
second section Page and it is generated here too, with nothing new written.
`unit.py` finds it by walking up from each product until a folder holding
`source/build.py` appears, which is how one resolver serves two companion
shapes without knowing about either.

WHAT CROSSES INTO THE MANUSCRIPT, and what does not. Everything under a
`#### P<n>.` heading is prose and travels. Everything else on the Page is
board-side apparatus and stops here:

    the division caption, its figure, its emoji line   the Page's furniture
    the `(one-line scan hook)` under a P heading       a preview, not a sentence
    every `> Value:` and `> Display:` lane             provenance, not prose
    every `[Q-Sec<unit><Kind>-<n>]` bracket            ties the number to the
                                                       board question that owes
                                                       it; the reader never
                                                       sees the board

A citation command is the one piece of LaTeX allowed to travel unchanged, so
`\\cite{TOADD}` reaches the .tex still unfilled and still visible.

USAGE
    python3 build.py            regenerate every section .tex in the group
    python3 unit.py build       the same thing, in dependency order
"""
import pathlib
import re

HERE = pathlib.Path(__file__).resolve().parent
SECTIONS = HERE.parent                     # sections/
GROUP = SECTIONS.parent                    # the QBt group folder

HEAD = re.compile(r"^(page-type|section_kind|provides):\s*(.*)$")
DIVISION = re.compile(r"^### (§[\d.]+) (.+)$")
PARAGRAPH = re.compile(r"^#### (P\d+)\.\s*(.+)$")
BRACKET = re.compile(r"\s*\[Q-[A-Za-z0-9]+-\d+\]")


def head(lines):
    out = {}
    for line in lines:
        if line.startswith("## "):
            break
        m = HEAD.match(line.strip())
        if m:
            out[m.group(1)] = m.group(2).strip()
    return out


def parse(lines):
    """Return (subsection title, [(P id, job, [sentences])]) pairs, in order."""
    out, fence, in_content, block = [], False, False, None
    for line in lines:
        if line.startswith("```"):
            fence = not fence
            continue
        if fence:
            continue
        if line.startswith("## "):
            in_content = line.strip() == "## Content"
            block = None
            continue
        if not in_content:
            continue
        m = DIVISION.match(line)
        if m:
            out.append((m.group(2).strip(), []))
            block = None
            continue
        m = PARAGRAPH.match(line)
        if m:
            block = (m.group(1), m.group(2).strip(), [])
            out[-1][1].append(block)
            continue
        if block is None:
            continue                       # caption, figure, emoji line
        text = line.strip()
        if not text or text.startswith(">"):
            continue                       # blank, or a provenance lane
        if text.startswith("(") and text.endswith(")"):
            continue                       # the paragraph's scan hook
        block[2].append(BRACKET.sub("", text))
    return out


def render(page, meta, body):
    kind = meta.get("section_kind", "section")
    tex = [
        "% --- GENERATED by sections/source/build.py · do NOT hand-edit ---",
        f"% source: {page.name}   ·   section_kind: {kind}",
        "% Sentence index is line position inside a paragraph block: the first",
        "% prose line after a `% P3.` comment is P3.S1, the next is P3.S2.",
        "% 🚫 FABRICATED. Every number below is invented and may not be cited.",
        "",
        f"\\section{{{kind.replace('-', ' ').title()}}}",
        "",
    ]
    for title, blocks in body:
        tex += [f"\\subsection{{{title}}}", ""]
        for pid, job, sentences in blocks:
            tex.append(f"% {pid}. {job}")
            tex += sentences
            tex.append("")
    return "\n".join(tex).rstrip() + "\n"


if __name__ == "__main__":
    for page in sorted(GROUP.glob("QBt*-for-section.md")):
        lines = page.read_text().splitlines()
        meta = head(lines)
        if meta.get("page-type") != "section":
            continue
        out = GROUP / meta["provides"]
        body = parse(lines)
        out.parent.mkdir(parents=True, exist_ok=True)
        out.write_text(render(page, meta, body))
        n = sum(len(s) for _, blocks in body for *_, s in blocks)
        print(f"{page.name}: {len(body)} subsections · "
              f"{sum(len(b) for _, b in body)} P · {n} sentences -> "
              f"{out.relative_to(GROUP)}")
