"""Write ref/workbench-table.md, the Design Workbench Table, from the ladder run cards (generated; never hand-edited).

    python cards_table.py            reads haipipe-design-workflow/references/run-cards.md, writes ../ref/workbench-table.md

One row per ladder card (`🔘 BUTTON   label · <Level> › <Space> · ^pattern · views <names>`), in card order, with the
columns of the table-workbench shape: Level · Space · View · Run type · Agent · Skill · Person signs · Folder. The
older board's cards (one-word Spaces) are not rows here; that page keeps ref/legacy/workbench-table-older.md.
"""
import re
from pathlib import Path

HERE = Path(__file__).resolve().parent
CARDS = HERE.parents[1] / "haipipe-design-workflow" / "references" / "run-cards.md"
OUT = HERE.parent / "ref" / "workbench-table.md"
BUTTON = re.compile(r"^🔘 BUTTON\s+(.+?) · (Block|Job|Task) › ([^·]+?) · (\^run-\S+)(?: · views (.+))?$")
WHERE = {"Block": "Block › runs/", "Job": "Job › runs/", "Task": "Task › runs/"}


def rows():
    out, card = [], None
    for line in CARDS.read_text(encoding="utf-8").splitlines():
        m = BUTTON.match(line)
        if m:
            label, level, space, pattern, views = m.groups()
            run = pattern.lstrip("^").rstrip("-") + ("-<target>" if pattern.endswith("-") else "")
            card = {"level": level, "space": space.strip(), "views": views or "every view", "label": label,
                    "run": run, "agent": "", "skill": "", "signs": ""}
            out.append(card)
        elif card is not None:
            for mark, key in (("🤖 AGENT", "agent"), ("🧩 SKILL", "skill"), ("✍️ SIGNS", "signs")):
                if line.startswith(mark):
                    card[key] = line[len(mark):].strip()
    return out


def main():
    rs = rows()
    lines = ["Design Workbench Table", "======================", "",
             "Generated by `../scripts/cards_table.py` from the ladder run cards "
             "(`haipipe-design-workflow/references/run-cards.md`); never edit it by hand: change a card and run the script.",
             "Shape and check: `skills/0_utils/table-workbench/SKILL.md`. Folder is where the Run's folder sits; a hard Run "
             "writes only its result/, a soft Run its level's own files and its passes. The older board page keeps "
             "`legacy/workbench-table-older.md`.", "",
             "| Level | Space | View | Run type | Agent | Skill | Person signs | Folder |",
             "|---|---|---|---|---|---|---|---|"]
    lines += [f"| {r['level']} | {r['space']} | {r['views']} | {r['label']} (`{r['run']}`) | {r['agent']} | {r['skill']} | "
              f"{r['signs']} | {WHERE[r['level']]}`{r['run']}/` |" for r in rs]
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT.name}: {len(rs)} rows")


if __name__ == "__main__":
    main()
