"""
Generate one folder per example, each holding the EXACT request and the EXACT
response, so a consumer can see what the two APIs do without running them.

    source .venv/bin/activate && source env.sh
    python .../describe-medication/examples/run_examples.py

Covers BOTH skills, because the interesting thing is the CHAIN: a logged row
becomes a drug, and an insulin drug becomes pharmacokinetics. Nothing here is
hand-written; a diff in any response.json IS a behaviour change.
"""
import json
import os
import pathlib
import sys
import urllib.error
import urllib.request

MED = os.environ.get("MEDNORM_URL", "http://127.0.0.1:8079").rstrip("/")
INS = os.environ.get("INSNORM_URL", "http://127.0.0.1:8080").rstrip("/")
HERE = pathlib.Path(__file__).resolve().parent
OUT = HERE / "api"

README_HEAD = """# describe-medication + describe-insulin — worked API examples

GENERATED by `run_examples.py`. Do not hand-edit; re-run it instead.

Each folder is one real call against a live service: the request that went out,
the response that came back, and a note saying what the case is for.

    cd api/<case> && bash curl.sh

The two services are a CHAIN, not siblings. `describe-medication` resolves a
logged row to a `DrugKey`; `describe-insulin` consumes that string. Nothing can
tell whether MedicationID 612997 is insulin until it has been resolved, so the
order is fixed.

"""


def ohio(k):
    return json.dumps({"MedicationType": k})


def sh(k):
    return json.dumps({"MedicationName": k})


CASES = [
    # ---- 1. the three dialects -----------------------------------------
    ("1-dialects/welldoc-id", "a bare WellDoc MedicationID", MED,
     "/normalize", {"item": "612997", "dose": 39},
     "386,373 rows look like this: an integer and a number, no drug name "
     "anywhere in the row. The name lives in a pooled lexicon built from every "
     "cohort's ImportedMedication export."),
    ("1-dialects/ohio-class", "OhioT1DM logs a CLASS, not a product", MED,
     "/normalize", {"item": "x", "dose": 1.5, "payload": ohio("Basal Insulin")},
     "5,026 rows. MedicationID is EMPTY -- zero distinct values in the whole "
     "cohort. Ingredient stays null because no product directory can resolve a "
     "therapeutic class, and MedSource says class_only rather than blaming the "
     "bank. IsInsulin is still true, so the row routes to describe-insulin."),
    ("1-dialects/shanghai-grams", "Shanghai writes the unit in the string", MED,
     "/normalize", {"item": "Non-insulin hypoglycemic agents",
                    "payload": sh("metformin 0.5 g")},
     "The log states grams; the pipeline stores milligrams. 'metformin 0.5 g' "
     "and 'metformin 500 mg' are one prescription and must not sort into two "
     "buckets three orders of magnitude apart."),
    ("1-dialects/shanghai-multidrug", "three drugs in one string", MED,
     "/normalize", {"item": "Non-insulin hypoglycemic agents",
                    "payload": sh("liraglutide 1.2 mg, acarbose 50 mg, metformin 0.5 g")},
     "736 Shanghai rows carry more than one drug -- the same shape as "
     "describe-food's item_list. The record reports the first component; the "
     "dialect layer keeps all three."),
    ("1-dialects/shanghai-csii", "the name is the DOSE", MED,
     "/normalize", {"item": "CSII - basal insulin (Novolin R, IU / H)",
                    "dose": 0.6, "payload": sh("0.6")},
     "2,176 pump rows. The drug is named by the CATEGORY (Novolin R) and the "
     "'name' field holds the dose. Note Ingredient is null -- the FDA Directory "
     "does not list Novolin R -- while DrugKey still carries it. That is the "
     "seam, and it is why these rows are not lost."),

    # ---- 2. the dose scale ---------------------------------------------
    ("2-dose/insulin-units", "39 means 39 units", MED,
     "/normalize", {"item": "612997", "dose": 39},
     "DoseUnit iu. The Dose column is a bare float and no column anywhere in "
     "the pipeline states its unit; the unit is a property of the DRUG."),
    ("2-dose/tablet-count", "1 means one tablet, not one milligram", MED,
     "/normalize", {"item": "155744", "dose": 1},
     "DoseUnit count. Median dose for non-insulin rows is exactly 1, because "
     "the app asks how many were taken. Reading that as milligrams would be "
     "wrong by three orders of magnitude."),
    ("2-dose/sentinel-255", "255 is uint8 overflow, not a dose", MED,
     "/normalize", {"item": "612997", "dose": 255},
     "6,039 rows carry Dose 255 and the 99th percentile of the whole column IS "
     "255. Typed as a sentinel: the value is withheld and MedConf is MISS."),
    ("2-dose/unknown-drug-no-unit", "no drug, no unit, no basis", MED,
     "/normalize", {"item": "999999999", "dose": 5},
     "The dose is real and its unit is unknowable, so DoseUnit and DoseBasis "
     "are both null. A null unit is what stops a consumer summing it across "
     "drugs."),

    # ---- 3. the resolution ladder --------------------------------------
    ("3-ladder/ndc-good", "the drug's own code -> GOOD", MED,
     "/normalize", {"item": "155744", "dose": 1},
     "Tier A. The NDC resolved in the FDA's own file. There is no better "
     "evidence, so this is the one tier that earns GOOD."),
    ("3-ladder/generic-ok", "a name match is OK, never GOOD", MED,
     "/normalize", {"item": "606257", "dose": 10},
     "Tier B, 69.9% of rows. Two products can share a generic name and differ "
     "in salt, strength and route, so a name match answers 'which drug' and "
     "not 'which product'."),
    ("3-ladder/brand-ok", "a brand resolves to its ingredient", MED,
     "/normalize", {"item": "582255", "dose": 1},
     "Tier C. 'Jardiance 25 MG tablet' -> Empagliflozin."),

    # ---- 4. the chain into insulin -------------------------------------
    ("4-insulin/rapid", "an ultra-rapid analogue", INS,
     "/normalize", {"item": "Insulin lispro-aabc"},
     "108,516 administrations, the single largest drug in the whole corpus. "
     "Note it does NOT collapse onto plain lispro: the longest alias wins, so "
     "an ultra-rapid formulation is not priced as an ordinary one."),
    ("4-insulin/peakless", "glargine has no peak, and says so", INS,
     "/normalize", {"item": "Insulin glargine"},
     "PeakMin is null, not 0. A consumer reading 0 would place the maximum "
     "effect at the moment of injection. Peakless is a property of the drug."),
    ("4-insulin/class-only", "OhioT1DM's class, served directly", INS,
     "/normalize", {"item": "basal insulin"},
     "describe-medication could not resolve this and describe-insulin can. "
     "That is the whole reason these are two skills and not one."),
    ("4-insulin/premix-biphasic", "a 70/30 mix is two curves", INS,
     "/normalize", {"item": "insulin aspart 70/30"},
     "Biphasic true. One (onset, peak, duration) triple describes a premix "
     "badly; the flag is how a consumer knows it is approximating."),
    ("4-insulin/combination", "Xultophy is insulin AND a GLP-1 agonist", INS,
     "/normalize", {"item": "insulin degludec and liraglutide"},
     "PKConf ALIAS, not OK. The insulin component is real and resolvable; "
     "calling the row plain degludec would hide the second drug."),
    ("4-insulin/patient-dia", "a DIA measured on THIS patient", INS,
     "/normalize", {"item": "basal insulin", "dia_hours": 7.0},
     "The only way to reach GOOD. WellDoc's MedPrescription carries a measured "
     "duration of insulin action for 15.7% of prescriptions. Note OnsetMin is "
     "unchanged -- only the duration was measured, and PKSource keeps both "
     "halves visible."),
    ("4-insulin/not-insulin", "a clean miss", INS,
     "/normalize", {"item": "metformin"},
     "Nothing invented. A non-insulin returns the same eight fields, all null, "
     "with PKConf MISS."),

    # ---- 5. caller errors ------------------------------------------------
    ("5-errors/length-mismatch", "doses shorter than items", MED,
     "/normalize/batch", {"items": ["612997", "606257"], "doses": [10]},
     "422, not a silent zip truncation. Truncating would re-pair every row "
     "after the missing one onto the wrong drug, with no exception raised."),
]


def post(base, path, body):
    req = urllib.request.Request(base + path, data=json.dumps(body).encode(),
                                 headers={"Content-Type": "application/json"})
    try:
        with urllib.request.urlopen(req, timeout=120) as r:
            return r.status, json.loads(r.read())
    except urllib.error.HTTPError as e:
        return e.code, json.loads(e.read())


def main():
    for base, label in ((MED, "describe-medication"), (INS, "describe-insulin")):
        try:
            urllib.request.urlopen(base + "/healthz", timeout=10)
        except Exception as e:
            print(f"{label} unreachable at {base}: {e}")
            return 1
    lines, group = [], None
    for slug, title, base, path, body, why in CASES:
        g = slug.split("/")[0]
        if g != group:
            group = g
            lines.append(f"\n## {g}\n")
        d = OUT / slug
        d.mkdir(parents=True, exist_ok=True)
        status, resp = post(base, path, body)
        svc = "describe-insulin" if base == INS else "describe-medication"
        env = "INSNORM_URL" if base == INS else "MEDNORM_URL"
        (d / "request.json").write_text(json.dumps(body, indent=2) + "\n")
        (d / "response.json").write_text(json.dumps(resp, indent=2) + "\n")
        (d / "curl.sh").write_text(
            "#!/usr/bin/env bash\n# Run from inside this folder.\n"
            f'curl -sS "${{{env}:-{base}}}{path}" \\\n'
            '  -H "content-type: application/json" \\\n'
            '  --data @request.json | python3 -m json.tool\n')
        (d / "NOTE.md").write_text(
            f"# {title}\n\nservice: {svc}\nHTTP {status}\n\n{why}\n")
        lines.append(f"- [`{slug}`](api/{slug}) — {title} · {svc} (HTTP {status})")
        print(f"  {status}  {svc:22s} {slug}")
    (HERE / "README.md").write_text(README_HEAD + "\n".join(lines) + "\n")
    print(f"\n{len(CASES)} cases -> {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
