"""s12 · Job level: s12-paper-job.excalidraw, a paper version's tab on the shared frame (one version for
one venue: its telling, its Sections, its build), its Spaces as full screens with "on disk" under each,
then Guide › Method opened from the Job tab (JL 261007: "add the s11 s12 s13 like b11").

It draws Q01's proposal for a version Job (s01-paper-ladder): the §8 Narrative is the version face's
## Narrative (Q04), its Work Details are its Sections (Main · Appendix · Letters, each row its Section map), its
Delivery is the built version (? Q02). A Section opens the Task tab (s13). Placeholders only; written
through canvas.write, so every mark a person adds survives a rebuild.

    python build_s12_paper_job.py [out.excalidraw]
"""
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent / "_build"))
import paper_ui as U  # noqa: E402

GRAY, RED, INK, MONO = U.GRAY, U.RED, U.INK, U.MONO

MOVES = [("(no version today)", "Job tab: one version, jNN_v<MMDD>_<desk>/, the Board's six Spaces"),
         ("(none)", "Audience Report › Questions: one-minute story · why this venue · principles"),
         ("Story §8 Section Narrative", "the face's ## Narrative · Audience Report › Draft-Main, release G3"),
         ("Delivery › Rounds (concern table)", "Audience Report › Comments: each comment, written back ?"),
         ("Sections › Main · Appendix · Table", "Work Details › Main · Appendix · Letters, each row its map"),
         ("Sections › Evidence", "Work Details: each Section row's evidence count; the items on its Task tab"),
         ("Delivery › Preview · Artifacts · Checks", "Delivery: this version built, checked (G4) ? (Q02)"),
         ("Delivery › Cover letter", "Audience Report › Cover letter (as read) · Letters (its Page) · Delivery (built)"),
         ("Delivery › Rounds", "Audience Report › Comments: a report of type comments, reports/qNN_<kind>-<MMDD>/")]

# what changed on this drawing, in green on the drawing (JL 261007: "add the short green comments to where we made
# the changes"); the same ✎ lines sit in place on each screen
CHANGES = ["each Space a row, its explanation on the right",
           "Audience Report: Questions · Draft-Main · Draft-Appendix · Comments · Cover letter, each a list of cards",
           "Comments: Review Items (Review-<slug> citing R1.1 · E1.2) in place of the Rounds concern table",
           "Delivery: item cards, the old page's Preview · Artifacts · Checks inside them; no LaTeX · Word tab row",
           "names: a version j0N_v<MMDD>_<desk>/, its Tasks t0N_ Main · t2N_ Appendix · t3N_ Letters",
           "a version carries its Space folders: studio/ · reports/ · runs/",
           "a comments batch is not a Task; t31 cover letter · t32 response",
           "a Story is not a Job (j00_story dropped); the next version copies j01's authored files",
           "comments are a report of type comments: reports/qNN_<kind>-<MMDD>/ in the version that answers them",
           "§8 and the compile order: the version face's ## Narrative; the Story is studio topics + Board Questions (Q04)",
           "haipipe-paper-round renamed haipipe-paper-comments"]


def description(cx, cy, cw):
    y = U.lines(cx, cy, [
        ("j02_v<MMDD>_<desk>.md", INK, MONO),
        ("venue: <venue B> · deadline <date> · double blind", INK),
        ("tells: studio/sNN-story-<telling>/", INK),
        ("from: j01_v<MMDD>_<desk> · answers: reports/q04_editor-decision-<MMDD>", INK),
        ("state: drafting · next: release t05 (G3)", INK),
        ("task_groups: Main · Appendix · Letters", INK),
        ("", GRAY),
        ("the venue's rules, read from venues/<venue B>/call.md:", GRAY),
        ("  words  <used> of <limit>     displays  4 of 6", INK),
        ("  abstract  <n> of <limit>     references  <n> of <limit>", INK),
        ("? words over the limit: a check Run, or shown here only", RED)])
    return U.changed(cx, y + 6, ["the face is j02_v<MMDD>_<desk>.md: a version is dated by its send (was j02_v2_)",
                                 "from · answers: now real fields; tells: no j00_story/",
                                 "tells: a studio topic, sNN-story-<telling>/ (was a Story Page, Q04)"])


def studio(cx, cy, cw):
    y = U.card(cx, cy, cw, "s01-paper-map   this version's Sections, paragraphs and evidence",
               "generated by excalidraw-section from the plans · view only", mark="▾")
    y = U.drawing_box(cx + 20, y, cw - 40, 340, "[ the paper map: groups → Sections → paragraphs → evidence cards ]")
    return U.lines(cx, y + 6, [("optional at Job level: a version needs no drawing of its own", GRAY)])


AR_TABS = ["Questions", "Draft-Main", "Draft-Appendix", "Comments", "Cover letter"]   # the Audience Report's third row (JL 261007)


def qwr(cx, cy, cw, heads, rows, cols=None):
    """The rows as the old paper page's item cards (JL 261007: "this is very ugly … All the things to be the
    card"): one closed card per row, › its label, a gray line of what it carries and its work, its state on the
    right; the first card open. `heads` name what the three parts are; a line starting "?" draws red."""
    U.text(cx, cy, "cards: " + " · ".join(h.split(" · ")[0].lower() for h in heads), 13, GRAY)
    y = cy + 26
    for n, (q, work, report) in enumerate(rows):
        red = any(l.startswith("?") for l in q)
        label = q[0].lstrip("? ").replace(" ↗", "")
        sub = " · ".join([l.lstrip("? ") for l in q[1:]] + [l.lstrip("? ") for l in work if l not in ("—",)])
        state = report[-1].lstrip("? ") if report else ""
        opened = n == 0 and len(report) > 1
        h = 66 + (24 * (len(report) - 1) + 12 if opened else 0)
        U.base("rectangle", cx, y, cw, h, RED if red else GRAY, 1, dashed=red, rough=0)
        U.text(cx + 14, y + 10, ("▾ " if opened else "› ") + label, 16, RED if red else INK)
        U.text(cx + 34, y + 38, sub[:110], 13, RED if red else GRAY)
        U.text(cx + cw - 16 - len(state) * 8, y + 12, state, 14, RED if red else INK)
        if opened:
            for k, line in enumerate(report[:-1]):
                U.text(cx + 34, y + 66 + k * 24, line, 14, INK)
        y += h + 8
    return U.changed(cx, y + 2, ["cards in the old paper page's look (was Question │ Work │ Report rows)"])


def qrows(cx, cy, cw, heads, rows, cols=(0, 330, 700)):
    """Questions in the question format, the Insight rows (JL 261007: "put things here in the question format"):
    Question │ Task Work │ Report, each cell a few lines; a line starting "?" draws red. Returns the bottom."""
    for h, c in zip(heads, cols):
        U.text(cx + c + 10, cy, h, 14, GRAY)
    y = cy + 28
    for cells in rows:
        h = 24 * max(len(c) for c in cells) + 18
        U.base("rectangle", cx, y, cw, h, GRAY, 1, rough=0)
        for c in cols[1:]:
            U.path([(cx + c, y), (cx + c, y + h)], arrow=False, color=GRAY)
        for cell, c in zip(cells, cols):
            for k, line in enumerate(cell):
                U.text(cx + c + 10, y + 9 + k * 24, line, 14, RED if line.startswith("?") else INK)
        y += h + 8
    return y


def questions(cx, cy, cw):
    """What a reader of this send asks, each answered from its work (JL 261007: "Audience report should try to
    answer the questions … why this venue, what are the writing principles … the one minute story")."""
    y = qrows(cx, cy, cw, ["Logic · the question", "Work · the Jobs, Tasks and Runs", "Report · what it says"], [
        (["J1 · What is the one-minute story? ↗"], ["studio/sNN-story-<telling> face", "this version's Abstract · Intro"],
         ["5 sentences: gap · question · data ·", "finding · why it matters   ✓"]),
        (["J2 · Why this venue? ↗"], ["venues/<venue B>/call.md", "playbook: desk taste · fit signals"],
         ["fits: <reader> · <contribution type>", "risk: <desk-reject signal>   draft"]),
        (["J3 · Which writing principles", "does it follow? ↗"], ["playbook style · section norms",
                                                                    "method card: By reader expectations"],
         ["order · word budget · abstract form ·", "one claim per paragraph   ✓"]),
        (["J4 · Is it ready to send? ↗"], ["Section CHECKs · Delivery › Checks"], ["3 of 4 checks · G4 not yet   draft"]),
        (["? J5 · What changed since the last", "send? (a revision only)"], ["the round's Comments ·", "the Sections' revise Runs"],
         ["? one paragraph per change"])])
    y = U.lines(cx, y + 8, [("each question is a report: reports/qNN_<topic>/ in this Job", GRAY)])
    return U.changed(cx, y + 6, ["new view: the send's own questions (was no view)",
                                 "b03's own question row, the base frame's (was cards, then the Insight rows)"])


def draft_main(cx, cy, cw):
    """The paper as read, one old Narrative card per Section in reading order (JL 261007: "All the things to be
    the card"): the label is its reader question, the subline its number and name, the status its state; opened,
    its ## Narrative fields (job · must establish · release G3) and its draft and drawing links."""
    y = qwr(cx, cy, cw, ["Section · its reader question", "its number and name", "its state"], [
        (["Does the treatment change the outcome, and for whom?", "3 t03_results · carries C1 · C2"],
         ["3 value · 2 display · 4 of 6 ¶"],
         ["job: the result the paper stands on", "must establish: C1 · C2   release G3: ✓",
          "draft ↗ · drawing ↗ (the Section map)", "drafting"]),
        (["Why does it matter, and what is the gap?", "1 t01_introduction · carries C0"],
         ["3 cite · 5 of 5 ¶"], ["written · CHECK ✓"]),
        (["What does it mean, and where does it stop?", "4 t04_discussion · carries C2 · C3"],
         ["not released (G3)"], ["planned"])])
    y = U.lines(cx, y + 6, [("each card is a row of the version face's ## Narrative; its draft and its drawing open "
                             "from the card", GRAY)])
    return U.changed(cx, y + 6, ["the old Narrative cards, the reader question as the label (was Q │ W │ R rows "
                                 "with the draft and drawing panes)",
                                 "the cards read the version face's ## Narrative (Q04)"])


def cover_letter(cx, cy, cw):
    """The cover letter as the editor reads it (JL 261007: "we should add a new things name cover letter … It should be
    here"): each paragraph, the question or venue rule it answers, and its text; then the letter as built."""
    y = qwr(cx, cy, cw, ["Paragraph · what it says", "Work · the question or rule it answers",
                         "Report · the text, as the editor reads it"], [
        (["¶1 · what we submit"], ["the face: title · article type · venue"], ["\"<we submit …>\"", "✓"]),
        (["¶2 · the one-minute story"], ["J1 · the Story's Seed and claims"], ["\"<the paper in five lines>\"", "✓"]),
        (["¶3 · why this venue"], ["J2 · the venue's playbook · its readers"], ["\"<why here>\"", "draft"]),
        (["¶4 · declarations"], ["venues/<venue>/call.md: originality ·", "conflicts · data · funding"],
         ["\"<the statements>\"", "✓"]),
        (["? ¶5 · suggested reviewers"], ["? the venue asks for them"], ["—", "open"])], cols=(0, 330, 700))
    y = U.drawing_box(cx, y + 8, cw, 150, "[ the letter as built: delivery/cover-letter/<letter>.pdf, embedded ]")
    y = U.lines(cx, y + 4, [("it never states a number the manuscript does not print, nor a fact the venue "
                             "page does not hold", GRAY)])
    return U.changed(cx, y + 6, ["new view: the cover letter as the editor reads it (was Delivery › Cover letter)"])


def comments(cx, cy, cw):
    """The review, as Review Items (JL 261007): each row one named item, "N. Review-<slug>", that cites the
    original points it answers (R1.1 = reviewer 1, point 1; E1.2 = the editor, point 2; A1.1 = a coauthor);
    Review Item │ Work │ Report; the item ↗ opens a pop-out with the cited points in full, the passage as sent
    and now, the Run and the reply."""
    y = qwr(cx, cy, cw, ["Review Item · the points it cites · where it lands", "Work · the Run that answers it",
                         "Report · the reply, in the letter"], [
        (["1. Review-causal-claim ↗", "cites R1.1 · R1.3 · E1.2", "→ t03 ¶2 · claim C2"],
         ["run-revise-causal-claim", "¶2 rewritten · before/after"], ["\"We now <…>\" · quotes ¶2", "answered ✓"]),
        (["2. Review-missing-subgroup ↗", "cites R2.1 · R2.4", "→ work Task t04 · t03 ¶4"],
         ["t04 › r05 (a new hard Run)", "E06 value added to ¶4"], ["\"We added <…>\"", "applied · CHECK next"]),
        (["3. Review-intro-length ↗", "cites A1.2", "→ t01 ¶1"],
         ["declined"], ["\"<the reason>\"", "declined · rationale ✓"]),
        (["? 4. Review-<slug> ↗", "cites E1.1", "? not routed yet"], ["—"], ["—", "open"])],
        cols=(0, 430, 760))
    y = U.lines(cx, y + 8, [("every original point is cited by one item; a Run names its item "
                             "(run-revise-causal-claim); a Section's tab lists the items on it", GRAY),
                            ("? the response letter is the items in order, each quoting the points it cites", RED)])
    return U.changed(cx, y + 6, ["rows are Review Items, N. Review-<slug> citing R1.1 · E1.2 (was one row per point)",
                                 "moved here from Delivery › Rounds; written by haipipe-paper-comments (was -round)",
                                 "a batch is not a Task (was RD<NN>-… · t31_editor-decision)",
                                 "Run types from run-cards.md: Add comments (was Add a review) · Route · Reply",
                                 "it is a report of type comments: reports/qNN_<kind>-<MMDD>/, page-type: comments"])


def sections(cx, cy, cw):
    y = cy
    for name, state, ev in [("t01_intro", "written · CHECK ✓", "3 cite"),
                            ("t02_method", "written · CHECK ✓", "1 value · 2 cite"),
                            ("t03_results", "drafting · 4 of 6 ¶", "3 value · 2 display"),
                            ("t04_discussion", "planned", "—")]:
        U.base("rectangle", cx, y, cw, 96, GRAY, 1, rough=0)
        U.text(cx + 14, y + 10, name + " ↗", 16, INK, MONO)
        U.text(cx + 14, y + 40, state, 14, INK)
        U.text(cx + 14, y + 64, "evidence: " + ev, 13, GRAY)
        U.base("rectangle", cx + 420, y + 10, cw - 440, 76, GRAY, 1, dashed=True, rough=0)
        U.text(cx + 440, y + 38, "▢ the Section's map, embedded, view only", 13, GRAY)
        y += 106
    y = U.lines(cx, y + 10, [("pick a Section → the Task tab (s13)", GRAY)])
    return U.changed(cx, y + 6, ["Sections named t0N_<title>/ by print order (was S-<desk>-Main-N-<Title>/)"])


def letters(cx, cy, cw):
    y = U.table(cx, cy, cw, ["Page Task", "for", "state"], [0, 420, 640],
                [("t31_cover-letter/ ↗", "the editor", "drafting"),
                 ("t32_response/ ↗", "the reviewers: the batch", "drafting")], mono=(0,))
    y = U.lines(cx, y + 20, [("each is a Page Task: the same six Spaces as a Section", GRAY)])
    return U.changed(cx, y + 6, ["t3N_ is Letters: t31 cover letter · t32 response (was tNN_, open)",
                                 "the comments a response answers are a report of type comments, reports/qNN_…, not a Task",
                                 "Run types from run-cards.md: Add a letter · Cover letter · Response"])


def runs(cx, cy, cw):
    return U.table(cx, cy, cw, ["Run", "type", "target", "state"], [0, 380, 560, 760],
                   [("run-narrative-s3/", "narrative", "t03 row", "closed · p01"),
                    ("run-compile-v2/", "compile", "delivery/", "ok · p04"),
                    ("run-check-submit/", "check", "delivery/", "open · p01"),
                    ("run-delivery-latex/", "delivery", "delivery/latex", "ok · p04"),
                    ("t03 › run-section-c2", "from below", "Section", "open")], mono=(0,))


def _group(cx, y, name):
    U.text(cx, y, name, 16, INK)
    return y + 30


def delivery(cx, cy, cw):
    """Delivery as item cards (JL 261007: "I want the delivery should be item card based"): one card per thing that
    leaves the Job, under its group; a card opens to its content. The paper card is open: the old page's Preview,
    the PDF embedded, then its Artifacts."""
    y = _group(cx, cy, "Manuscript")
    y = U.card(cx, y, cw, "paper.pdf · LaTeX     built · stale · <n> KB · <date>  ↗",
               "from <n> Section fragments in Narrative order · the kit of <venue B>", mark="▾")
    y = U.drawing_box(cx + 20, y - 4, cw - 20, 210, "[ the built PDF, embedded ]")
    y = U.table(cx + 20, y, cw - 20, ["printed", "label", "from the Section"], [0, 150, 440],
                [("Figure 1", "fig:<label>", "t01_introduction"),
                 ("Table 1", "—", "t03_<title>")], mono=(2,), h=26)
    y = U.card(cx, y + 8, cw, "paper.docx · Word     built · <date>", "its PDF twin is the preview")
    y = _group(cx, y + 4, "Letters")
    y = U.card(cx, y, cw, "cover letter     built · ready", "the Letters Page, as built (PDF · DOCX)")
    y = _group(cx, y + 4, "Checks")
    y = U.card(cx, y, cw, "submission readiness     DRAFT · <n> of <n> Sections ready · G4 not yet",
               "opens to the facts, the build's checks and each Section (below)")
    y = _group(cx, y + 4, "Sent")
    y = U.card(cx, y, cw, "reports/q01_<kind>-<MMDD>/sent/     frozen · <n> files · <date>",
               "Send froze it with its comments report; released/ when the answer goes back")
    return U.changed(cx, y + 4, ["item cards, one per thing that leaves the Job (was LaTeX · Word · Cover letter · Rounds tabs)",
                                 "the paper card holds the old Preview and Artifacts",
                                 "Send is a run card; the Sent card is the frozen build in its comments report (was ?)"])


def checks(cx, cy, cw):
    """The same Delivery with the Checks card open: as the old page read them from build-manifest.json."""
    y = _group(cx, cy, "Manuscript")
    y = U.card(cx, y, cw, "paper.pdf · LaTeX     built · stale · <n> KB · <date>  ↗", "opens to its preview")
    y = U.card(cx, y, cw, "paper.docx · Word     built · <date>", "its PDF twin is the preview")
    y = _group(cx, y + 4, "Letters")
    y = U.card(cx, y, cw, "cover letter     built · ready", "the Letters Page, as built (PDF · DOCX)")
    y = _group(cx, y + 4, "Checks")
    y = U.card(cx, y, cw, "submission readiness     DRAFT · <n> of <n> Sections ready · G4 not yet",
               "the facts · the build's checks · each Section", mark="▾")
    y = U.table(cx + 20, y - 4, cw - 20, ["fact", "value"], [0, 230],
                [("main text", "<n> words · limit <n>"), ("citations", "<n> cited · <n> bib entries"),
                 ("pages ready", "<n> of <n> · not ready: …"), ("submission", "DRAFT · G4 not yet: <blockers>")], h=24)
    y = U.table(cx + 20, y + 6, cw - 20, ["check", "result"], [0, 400],
                [("master · bibliography · citations resolved", "✓"), ("outputs rendered · latexmk · docx", "✓"),
                 ("the human decision", "✗")], h=24)
    y = U.table(cx + 20, y + 6, cw - 20, ["Section", "fragment", "ready", "notes"], [0, 380, 490, 590],
                [("t01_introduction", "✓", "✗", "outline not approved")], mono=(0,), h=24)
    return U.changed(cx, y + 10, ["new view: the Checks card open, as the old page read build-manifest.json"])


SCREENS = [
    ("Description", U.third(["Version", "Venue rules"], "Version"), ["Update the version", "Check the rules"], "",
     description, [("j02_v<MMDD>_<desk>/j02_v<MMDD>_<desk>.md", "the face: venue · deadline · Story · state"),
                   ("venues/<venue B>/call.md (the Board's)", "the rules it is held to")]),
    ("Idea Studio", None, ["Redraw the paper map"], "", studio,
     [("j02_v<MMDD>_<desk>/studio/s01-paper-map/", "? generated, or at the Board only")]),
    ("Audience Report", U.third(AR_TABS, "Questions"), ["Ask a Question", "Write the report", "Review the report"], "",
     questions, [("j02_v<MMDD>_<desk>/j02_v<MMDD>_<desk>.md  ## Questions", "J1 … J5, the register"),
                 ("j02_v<MMDD>_<desk>/reports/qNN_<topic>/", "one report per question"),
                 ("venues/<venue B>/ · the venue's playbook", "what J2 and J3 read")]),
    ("Audience Report", U.third(AR_TABS, "Draft-Main"), ["Narrative review", "Release a Section"], "", draft_main,
     [("j02_v<MMDD>_<desk>/j02_v<MMDD>_<desk>.md  ## Narrative", "the reading order and claims; the build's order"),
      ("t0N_<title>/delivery/web/", "the rendered draft (Report)"),
      ("t0N_<…>/studio/<stem>-sections.excalidraw", "its logic and narrative, drawn (Report)")]),
    ("Audience Report", U.third(AR_TABS, "Comments"), ["Add comments", "Route an item", "Reply to an item"], "",
     comments, [("j02_v<MMDD>_<desk>/reports/qNN_<kind>-<MMDD>/…md  ## Review Items", "one row per Review-<slug>: cites · lands on · work · reply · state"),
                ("reports/qNN_<kind>-<MMDD>/feedback/ · sent/", "the points as received R1.1 · E1.2 · the build reviewed"),
                ("reports/qNN_<kind>-<MMDD>/sent/", "the build as sent: the passage before"),
                ("t0N_<…>/runs/run-revise-<slug>/", "the Run an item names; its ledger: before/after")]),
    ("Audience Report", U.third(AR_TABS, "Cover letter"), ["Write the cover letter", "Check the letter"], "",
     cover_letter, [("j02_v<MMDD>_<desk>/t31_cover-letter/", "its source: a Page Task in Letters"),
                    ("j02_v<MMDD>_<desk>/delivery/cover-letter/", "the letter as built (PDF · DOCX)"),
                    ("venues/<venue B>/call.md", "the declarations the venue asks for")]),
    ("Work Details", U.third(["All", "Main", "Appendix", "Letters"], "Main"), ["Add a Section", "Draft runs"], "",
     sections, [("j02_v<MMDD>_<desk>/t0N_<title>/", "a Section: a Page Task (s13)"),
                ("t0N_<…>/studio/<stem>-sections.excalidraw", "its map, embedded in the row")]),
    ("Work Details", U.third(["All", "Main", "Appendix", "Letters"], "Letters"), ["Add a letter", "Cover letter", "Response"], "",
     letters, [("j02_v<MMDD>_<desk>/t31_cover-letter/", "a Page Task"),
               ("j02_v<MMDD>_<desk>/t32_response/", "a Page Task: the reply, item by item"),
               ("j02_v<MMDD>_<desk>/reports/qNN_<kind>-<MMDD>/", "the comments it answers: a report, type comments")]),
    ("Runs", U.third(["All", "narrative", "compile", "check", "delivery", "from below"], "All"),
     ["Update the version"], "", runs,
     [("j02_v<MMDD>_<desk>/runs/README.md", "the run types it has"),
      ("j02_v<MMDD>_<desk>/runs/run-<type>-<target>/", "run.yaml · ticket .md · passes/")]),
    ("Delivery", None, ["Build", "Check", "Send"], "", delivery,
     [("j02_v<MMDD>_<desk>/delivery/paper-build.toml", "order · venue kit · names"),
      ("j02_v<MMDD>_<desk>/delivery/<paper>.pdf · latex/ · word/", "the Manuscript cards, generated, never edited"),
      ("j02_v<MMDD>_<desk>/delivery/cover-letter/", "the Letters card"),
      ("j02_v<MMDD>_<desk>/delivery/display-register.md", "every table and figure as printed")]),
    ("Delivery", None, ["Build", "Check", "Send"], "", checks,
     [("j02_v<MMDD>_<desk>/delivery/build-manifest.json", "the Checks card: facts, checks, each Section")]),
    U.guide_method("Job"),
]

# the text beside each screen, one list per screen in SCREENS' order (JL 261007: "in the right you can add many
# text to explain them"); a paragraph with "?" is a proposal or open point and draws red
NOTES = [
    [("What it is", "The version's face, j02_v<MMDD>_<desk>.md: one send of the paper. It says which Story version it "
      "tells, to which venue, by when, and where it stands. Everything else on the Job tab hangs from it."),
     ("Its fields", "type (manuscript) · venue · deadline · tells (studio/sNN-story-<telling>/) · "
      "state · next step · task_groups, and two that draw the line between sends: from (the send it follows) "
      "and answers (the comments batch it answers)."),
     ("✎ 261007", "Named j02_v<MMDD>_<desk>, dated by its send; j00_story/ is gone: a Story is not a Job. A new "
      "version starts as a copy of the last one's authored files (faces, drafts, drawings), never its results, runs "
      "or builds. The telling it tells is a studio topic, sNN-story-<telling>/ (Q04)."),
     ("Venue rules", "The second view reads the Board's venues/<venue B>/call.md, frozen on the date it was read: "
      "the word and display limits, the format, the review rules. The limits are counted live against the "
      "Sections, so going over shows here before Build does."),
     ("Runs", "Update the version edits the face. Check the rules re-reads call.md; a rule that changed since the "
      "send opened draws red, and the person decides whether the send follows it.")],
    [("What it is", "Optional at the Job level: the version's own drawings. The one that earns its place is the "
      "paper map, drawn by excalidraw-section from every Section's plan and Evidence Items: groups, Sections, "
      "paragraphs, each Bullet a row with its evidence cards."),
     ("Why per version", "Two versions of one Story may tell it in a different order or drop a Section; each "
      "version's map shows its own telling. It is generated, view only; Redraw the paper map rebuilds it."),
     ("Open", "? Keep one map on the Board instead, showing the version in view, and leave the Job's Idea Studio "
      "empty unless a person draws there.")],
    [("What it is", "The Audience Report answers what a reader of this send asks, in the Block's shape: Question │ "
      "Work │ Report. The questions are the send's own: the one-minute story, why this venue, which writing "
      "principles it follows, whether it is ready, and in a revision what changed."),
     ("Why these questions", "They are what an editor, a coauthor or the person sending it needs before it goes: "
      "J1 is the paper in five sentences, J2 the venue's fit read from its playbook, J3 the rules of telling it "
      "follows. Each answer cites the work that supports it, so it can be checked."),
     ("On disk", "Each question is a report, reports/qNN_<topic>/ in this Job, registered in the face's ## Questions. "
      "Ask a Question adds one; Write the report and Review the report answer it."),
     ("Open", "? J5 (what changed) exists only for a revision, answered from the round's Comments."),
     ("✎ 261007", "A new view: the send's own questions in the question format (JL: \"put things here in the "
      "question format\"), Question │ Task Work │ Report rows as the Insight rows: the face's ## Questions first (a "
      "comments report among them), then the standing J1–J5 not asked yet. There was none before."),
     ("✎ 261007 · cards", "Questions stay rows; the other views are lists of the old paper page's item cards (JL: \"this is very ugly … All the "
      "things to be the card\"): closed, a card shows its label, a gray line and its state; opened, its fields.")],
    [("What it is", "Draft-Main is the paper as its reader meets it, one card per Section in reading order, the "
      "old page's Narrative cards. Draft-Appendix is the same for the Appendix."),
     ("A card", "Its label is the Section's reader question, its subline the number and name, its state on the "
      "right. Opened, it shows its ## Narrative fields (job, must establish, release G3) and links to the rendered "
      "draft and the Section's drawing."),
     ("✎ 261007", "The order and claims (the Story Page's §8) are this version's ## Narrative, and the build reads "
      "its compile order there (Q04): one Story, many tellings."),
     ("✎ 261007", "The old Narrative cards, the reader question as the label (was Question │ Work │ Report rows "
      "with the draft and drawing side by side, then the §8 table before that).")],
    [("What it is", "The review as Review Items, one card each (Review · the item · cites · where it lands · state; "
      "opened, its work and reply). "
      "An item is one concern, named and numbered (1. Review-causal-claim), and it cites the original points it "
      "answers: R1.1 is reviewer 1's first point, E1.2 the editor's second, A1.2 a coauthor's. Several "
      "reviewers raising one concern make one item, answered once."),
     ("The pop-out", "Click an item and it opens what the row leaves out: each cited point in the reviewer's own "
      "words, the passage as it was sent (from the frozen sent build) beside the passage now (from the Revise "
      "Run's before/after ledger), the Run, and the reply as it reads in the letter."),
     ("How it links", "An item routes to its owner: a passage to its Section (a revise Run named for the item, "
      "run-revise-causal-claim), a missing analysis to a work Task (a new hard Run), a claim to the Story. The "
      "Section's tab lists the items that land on it; an item's state is the Round's: open → routed → applied → answered (or declined · deferred)."),
     ("The check", "Every original point is cited by exactly one item, so none is left unanswered. ? The response "
      "letter is the items in order, each quoting the points it cites; all items replied closes it (G5)."),
     ("✎ 261007", "Moved here from Delivery › Rounds. Rows are Review Items named Review-<slug>, each citing "
      "R1.1 · E1.2 (was one row per point). haipipe-paper-round is renamed haipipe-paper-comments. "
      "A batch is a report of type comments, reports/qNN_<kind>-<MMDD>/ in the version that answers it, registered in its "
      "## Questions; its proposed questions become reports beside it.")],
    [("What it is", "The cover letter as the editor reads it, the first thing a send says about itself. One row "
      "per paragraph: what it says, the question or venue rule it answers (J1 the one-minute story, J2 why this "
      "venue, the declarations the call asks for), and its text with its state; then the letter as built, "
      "embedded."),
     ("Why in the Audience Report", "The letter is written for one reader, the editor, and it is made from the "
      "answers above: the Questions view is its Work. Delivery › Cover letter keeps the built files and their "
      "checks; Work Details › Letters keeps the Page it is written in."),
     ("Its rules", "It never states a number the manuscript does not print, nor a fact the venue page or "
      "paper-build.toml does not hold; a person approves it before the send."),
     ("✎ 261007", "A new view, moved here from Delivery › Cover letter. Its source is settled: the Page "
      "Task t31_cover-letter in Letters.")],
    [("What it is", "Its Tasks: the Sections, each a Page Task (s13), grouped Main · Appendix · Letters as the "
      "venue asks. The third row filters by group."),
     ("Each row", "A Section's state (written, drafting, planned), its CHECK, its evidence count, and its map "
      "embedded view only, so progress shows paragraph by paragraph, not as one word. Click a row and the "
      "Section opens on the Task tab."),
     ("Adding a Section", "Add a Section makes t0N_<title>/ from a released Narrative row; the venue's "
      "playbook gives its target length and shape. ? With the send model, opening the send (step 4) makes all "
      "of them at once from the venue's parts."),
     ("✎ 261007", "Sections are named t0N_<title> (Main) and t2N_<title> (Appendix, A = t21) by print order; "
      "was S-<desk>-Main-N-<Title>.")],
    [("What it is", "The letters a send carries, each a Page Task like a Section: the cover letter to the editor, "
      "and in a revision the response to the reviewers. Same six Spaces, same Runs: draft, check, deliver."),
     ("The response", "A review closes the send it reviewed. The response belongs to the next send, which answers them point by point and carries the revised Sections."),
     ("✎ 261007", "Named in the t3N_ band: t31_cover-letter, t32_response. A comments batch is not a Task "
      "(was RD<NN>-… or t31_editor-decision): it is a report of type comments, reports/qNN_<kind>-<MMDD>/.")],
    [("What it is", "The version's own soft Runs, by type: run-narrative-<section> (review a row), "
      "run-compile-<build> (assemble the paper), run-check-submit (readiness), run-delivery-<lane> (build a lane)."),
     ("From below", "The Sections' Runs roll up under 'from below', so every piece of writing in flight for this "
      "send shows in one list, each with its state and last pass."),
     ("No hard Runs", "A paper computes no facts: every number comes from a hard Run in a work or discovery Task, "
      "and the paper only quotes it. Each Run here is a folder with its run.yaml card, its ticket and passes/.")],
    [("What it is", "Delivery as item cards (JL 261007): one card per thing that leaves the Job, under its group: "
      "Manuscript (the PDF from LaTeX, the Word file), Letters (the cover letter, a response in a revision), "
      "Checks (submission readiness). A card's line says its state, size and when it was built; a click opens it."),
     ("An open card", "The paper card opens to the old page's Preview and Artifacts: the PDF embedded, then every "
      "table and figure as printed, with its label and the Section it comes from. The Word card shows the PDF the "
      "build draws beside the .docx."),
     ("No third row", "The old page's two rows of tabs (LaTeX · Word · Cover letter · Rounds × Preview · Artifacts · "
      "Checks) become cards, as a work Task's Delivery already shows its items. Rounds moved to the Audience "
      "Report's Comments."),
     ("Sent", "Send freezes the build into the comments report it goes out with, reports/qNN_<kind>-<MMDD>/sent/ "
      "(build.py send <qNN>; released/ when the answering build goes back). A Sent card shows it, then the "
      "decision; the Job closes and the next version starts from it."),
     ("✎ 261007", "Send is a run card now (was ? proposed): build.py send | release <qNN> (haipipe-paper g04)."),
     ("✎ 261007", "Item cards in place of the LaTeX · Word · Cover letter · Rounds tabs; the old page's "
      "Preview and Artifacts sit inside the paper card.")],
    [("What it is", "The same Delivery with the Checks card open, as the old page read them from "
      "build-manifest.json: the facts (main-text words against the limit, citations, pages ready and which are "
      "not, submission status and its blockers), the build's own checks, and one row per Section."),
     ("Ready to send", "The build stays DRAFT until every Section is checked. Check is submission readiness (G4), "
      "signed by a person; a Section row that is not ready names what stops it."),
     ("✎ 261007", "A new view: the Checks card open, as the old page's Checks tab showed them.")],
    [("What it is", "Guide › Method opened from the Job tab: the Job's steps open, the Block's and the Task's "
      "folded. The same Guide on every tab; the tab you came from decides which level opens."),
     ("The steps", "? 4 Open the send · 5 Write the Sections · 6 Deliver · ? 7 Close on the decision. Steps 4 and 7 "
      "are the send model's proposal and stay red until agreed (s31 draws the whole Guide)."),
     ("Method cards", "This level's card is By point-by-point response, for answering reviewers. ? A new card, "
      "By venue fit, would teach matching a venue's desk taste from its playbook.")],
]

POPOUTS = [("t03_results  ·  its report, full size", [
    ("[ the rendered draft · delivery/web/index.html, as a reader sees it ]", GRAY),
    ("[ logic + narrative · studio/<stem>-sections.excalidraw, view only ]", GRAY),
    ("Question: Does the treatment change the outcome, and for whom? · C1 · C2", INK),
    ("open the Section → Task tab (s13)", INK)]),
    ("1. Review-causal-claim  ·  a Review Item", [
    ("reports/q04_editor-decision-<MMDD>/…md#review-causal-claim · answered", GRAY),
    ("R1.1 · reviewer 1: \"<the point, word for word>\"", INK),
    ("R1.3 · reviewer 1: \"<the point, word for word>\"", INK),
    ("E1.2 · the editor: \"<the point, word for word>\"", INK),
    ("lands on: t03_results ¶2 ↗ · claim C2 ↗", INK),
    ("as sent:  \"<the passage, from delivery/sent/<date>/>\"", GRAY),
    ("now:      \"<the passage, from run-revise-causal-claim's ledger>\"", INK),
    ("reply: \"We now <…> (see Section 3, ¶2).\"", INK),
    ("? the letter quotes R1.1 · R1.3 · E1.2, then this one reply", RED)]),
    ("t03_results  ·  its Section map", [
    ("t03_results/studio/<stem>-sections.excalidraw", GRAY),
    ("[ paragraphs P1-P6 → each Bullet a row → its evidence cards ]", GRAY),
    ("generated from the plan and its Evidence Items · view only", GRAY),
    ("open the Section → Task tab (s13)", INK)]),
    ("build-manifest  ·  run-compile-v2 p04", [
        ("status DRAFT: t04 not written · t03 not checked", RED),
        ("order from Audience Report › Narrative", INK),
        ("kit: venues/<venue B>/kit/ · profile <venue B>", INK),
        ("outputs: paper.tex · paper.pdf · paper.docx", INK)])]

QUESTIONS = [
             "? Review Items: Review-<slug> rows citing R1.1 · E1.2, one table per batch",
             "? the built paper is this version's Delivery (Q02)",
             "? the paper map: per version Idea Studio, or only on the Board"]

if __name__ == "__main__":
    out = Path(sys.argv[1]) if len(sys.argv) > 1 else HERE / "s12-paper-job.excalidraw"
    U.level_drawing(out, "build_s12_paper_job.py", "Job",
                    "Job level: a paper version, one venue, its Sections and its build",
                    "Q01's proposal (s01): a version tells the Story for one venue; its Sections are Page Tasks; "
                    "it builds and submits.", MOVES, SCREENS, POPOUTS, QUESTIONS, notes=NOTES, changes=CHANGES)
