"""s13 · Task level: s13-paper-task.excalidraw, a paper Section's tab on the shared frame. A Section is a
Page Task (b03 s13-task-variants), so its Spaces are the base's Page Task views (servers/workbench/task-page); this drawing
marks what the paper adds to them, as haipipe-paper-section defines it: the reader contract in the face's
header (reader-question, entry and exit state, must-establish, story-row), the venue's rules in the
requirement record (V generated, W authored), and the
Section's own PDF with the piece the version pulls in and its readiness for the build. The "on disk" rows
follow the Section folders as they are today (results/run-display-…, runs/<name>.md); a Round is drawn as
a pop-out. Then Guide › Method opened from the Task tab. JL 261007: "add the s11 s12 s13 like b11".

Placeholders only; written through canvas.write, so every mark a person adds survives a rebuild.

    python build_s13_paper_task.py [out.excalidraw]
"""
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE.parent / "_build"))
import paper_ui as U  # noqa: E402

GRAY, RED, INK, TEAL, MONO = U.GRAY, U.RED, U.INK, U.TEAL, U.MONO

MOVES = [("a Section opens the Page workbench", "Task tab: the base's Page Task views, six Spaces (live 261007)"),
         ("Page › Draft › Table · Reading", "Audience Report › Table · Reading, with its form against the budget"),
         ("Page › Draft › Scratch · Revise", "Work Details › Draft-Scratch · Draft-Revise"),
         ("Page › Evidence › Citations · Displays · Values", "Work Details › Evidence-…"),
         ("Page › Draft › RoadMap Draw", "Idea Studio: the Section's logic, in its own studio/"),
         ("Page › Delivery › LaTeX", "Delivery: the Section's own PDF, the piece the version pulls in, ready · CHECK"),
         ("the face's header (story-row, reader-question, …)", "Description › Scope: the reader contract card"),
         ("the Outline's 📏 Requirement lens", "Description › Requirement: the venue's rules (V) and the Page's (W)"),
         ("<desk>-Round/RD<NN>-<event>/", "a comments batch: a report of type comments, <version>/reports/qNN_<kind>-<MMDD>/")]
PAPER = "paper adds"   # the tag on a line the paper theme adds to the base's Page Task screen


def tag(cx, y, cw):
    U.text(cx + cw - 110, y, "◆ " + PAPER, 13, TEAL)


GREEN, changed = U.GREEN, U.changed   # the shared green change notes (paper_ui)


def description(cx, cy, cw):
    """Scope: the reader contract, read from the face's header (haipipe-paper-section's required fields)."""
    y = U.card(cx, cy, cw, "t03_results   the reader contract",
               "read from the face's header · a stale story-row sends the Section back (HOLD)", mark="▾")
    y = U.lines(cx + 20, y, [("reader-question   <the one question this Section answers>", INK),
                             ("entry-state → exit-state   <what the reader knows> → <what is established>", INK),
                             ("must-establish   C1 · C2        must-refuse   <the misreading it blocks>", INK),
                             ("transition in · out   from §2 <…> · to §4 <…>", INK),
                             ("story-row   j02_v<MMDD>_<desk> ## Narrative / t03_results · row 3 of 5 · released (G3) ✓", INK),
                             ("structure   QBv<n>-<desk> §<n> Sec-4-Results · EXACT", INK, MONO)], gap=30)
    tag(cx, cy + 8, cw)
    y = changed(cx + 20, y + 4, ["story-row: the version face's ## Narrative row (was the Story Page's §8)"])
    return U.lines(cx, y + 16, [("Requirement (the next tab): V1-V<n> from the venue's section, generated;", GRAY),
                                ("W1-W<n> the Page's own rules, authored", GRAY)])


def studio(cx, cy, cw):
    y = U.card(cx, cy, cw, "s01-logic   the Section's logic, by hand", "drawing · the person's · studio/s01-logic/",
               mark="▾")
    y = U.drawing_box(cx + 20, y, cw - 40, 230, "[ the logic: claim left, reasons beside it, every Bullet a row ]")
    y = U.card(cx, y, cw, "s02-section-map   the Section map", "generated by excalidraw-section · view only · the row on the Job tab")
    return U.lines(cx, y + 6, [("empty until Draw the logic writes studio/s01-logic/ (no Section has one today)", GRAY)])


# today's Draft Table (servers/workbench/task-page/outline.py plan_card): a Reads line, then one folding row
# per paragraph, each with Bullet │ Draft columns (1 : 3); a Bullet is its address, [role], statement and
# its evidence chips; its Draft is the sentence written from it, or "Not drafted".
TABLE = [("C0.P1", "Opening overview", "", [("C0.P1", "Opening", "<the question, in one paragraph>", "", "<the opening paragraph>")]),
         ("C1.P1", "<paragraph job>", "+ 2 notes", [
             ("C1.P1.B1", "Claim", "<what the paragraph states>", "E01", "<sentence from B1>"),
             ("C1.P1.B2", "Evidence", "<the number behind it>", "E01 · E03", "<sentence from B2>")]),
         ("C1.P2", "<paragraph job>", "", [
             ("C1.P2.B1", "Display", "<what the reader sees>", "Display2", "<sentence pointing to Display 2>"),
             ("C1.P2.B2", "Contrast", "<how it differs>", "", "<sentence from B2>")]),
         ("C2.P1", "<paragraph job>", "+ 1 note", [
             ("C2.P1.B1", "Claim", "<the second finding>", "E04", "Not drafted")])]


def table(cx, cy, cw):
    U.text(cx, cy, "Reads draft/t03_results-draft-v<G>.<S>.md · Table ## 1 Structure · Reading ## 3 Draft", 13, GRAY, MONO)
    y, split = cy + 32, cx + cw // 4
    for para, job, notes, bullets in TABLE:
        U.base("rectangle", cx, y, cw, 30, GRAY, 1, rough=0)
        U.text(cx + 10, y + 6, f"▾ {para}   {job}", 15, INK)
        if notes:
            U.text(cx + cw - 110, y + 7, notes, 13, GRAY)
        y += 38
        U.text(cx + 10, y, "Bullet", 12, GRAY)
        U.text(split + 10, y, "Draft", 12, GRAY)
        U.path([(cx, y + 20), (cx + cw, y + 20)], arrow=False, color=GRAY)
        y += 26
        for addr, role, stmt, chips, draft in bullets:
            U.text(cx + 10, y, f"{addr} [{role}]", 12, INK, MONO)
            U.text(cx + 10, y + 18, stmt + (f"   {chips}" if chips else ""), 12, GRAY)
            U.text(split + 10, y + 6, draft, 15, GRAY if draft == "Not drafted" else INK)
            U.path([(split, y - 6), (split, y + 40)], arrow=False, color=GRAY)
            y += 46
        y += 8
    return y


def reviews(cx, cy, cw):
    """(JL 261007, via s12) The Review Items of the version's Round that land on this Section: one
    named item each, citing the original points it answers (R1.1 reviewer 1 point 1, E1.2 the editor,
    A1.2 a coauthor); the Round's states: open · routed · applied · answered · declined · deferred."""
    y = U.table(cx, cy, cw, ["Review Item", "Work", "Report"], [0, 470, 830],
                [("Review-<slug-a>  cites R1.1 · R2.3 · applied", "run-revise-<slug-a> · ¶2 changed", "reply P3"),
                 ("Review-<slug-b>  cites E1.2 · routed", "<task> › rNN", "No reply"),
                 ("Review-<slug-c>  cites R1.4 · A1.2 · answered", "run-revise-<slug-c> · ¶4 changed", "reply P5"),
                 ("Review-<slug-d>  cites R2.1 · declined", "declined", "reply P6")], h=40)
    return U.lines(cx, y + 16, [("rows of the comments report's ## Review Items whose lands on starts with this Section; one item gathers several points", GRAY),
                                ("↗ opens the item: the reviewers' words · the passage as sent beside it now · the Run · the reply", GRAY),
                                ("worked in Work Details › Draft-Revise by Revise edits (run-revise-<slug>)", GRAY)])


def questions(cx, cy, cw):
    """(JL 261007) The discussion questions kept while the Section is changed: each one a report in the
    Section's reports/, registered in its face, as a Block's Questions are."""
    # Question │ Work │ Report, as the Block's Audience Report (b03: one shape for a level's questions)
    y = U.table(cx, cy, cw, ["Question", "Work", "Report"], [0, 470, 830],
                [("Q01 · C1.P2  <does Display 2 belong here or in §4?>", "run-section-<slug> v3 · moved to C2.P1",
                  "q01_<topic> · answered"),
                 ("Q02 · C2.P1  <which baseline does the reader expect?>", "run-citation-<slug> · open",
                  "No answer"),
                 ("Q03 · C1.P1.B2  <is the number the one the venue asks?>", "run-value-e02 · W2 added",
                  "q03_<topic> · answered"),
                 ("Q04 · whole  <is the claim too strong for its evidence?>", "— · → the Story?", "No answer")],
                h=40)
    y = U.lines(cx, y + 16, [("one row per question in the face's ## Questions: where it was asked, the Runs that work it", GRAY),
                             ("Report ↗ opens reports/qNN_<topic>/: Answer · Evidence · Limits · Next", GRAY),
                             ("a paragraph's (+) note can become a question", GRAY)])
    return changed(cx, y + 6, ["Work: Run names without <MMDD>"])


# today's Page Runs view (servers/workbench/task-page/runs.py): count pills, then one group per kind, each
# Run a card (name · state dot · what it does, › opens its Result). A soft Run keeps its passes (p01, p02 …)
# in one file, so its name carries no date: runs/run-<type>-<slug>.md (JL 261007).
WRITING = [("Structure", [("Structure", "closed", "Agree the Page structure and evidence routes", "run-structure-<slug> · p01-p03")]),
           ("Scratch", [("Scratch · Paragraph · C2.P1", "open", "Capture rough thinking for paragraph C2.P1", "run-scratch-c2p1 · p01")]),
           ("Section", [("Section · t03_results", "open", "Review and modify t03_results", "run-section-<slug> · p01-p02")]),
           ("Paragraph", []),
           ("Revise", [("Revise · C1.P2", "closed", "Compare before and after for C1.P2 and settle each change", "run-revise-<slug-a> · p01")])]
EVIDENCE = [("Display", [("Display · E05 · <title>", "ok", "Run run-display-<slug> → Result", "run-display-<slug> · p01"),
                         ("Display · E06 · <title>", "ok", "Run run-display-<slug> → Result", "run-display-<slug> · p01")]),
            ("Citation", [("Citation · E03 · <author> <year>", "ok", "Run run-citation-<slug> → Result", "run-citation-<slug> · p01")]),
            ("Value", [("Value · E04 · <the number>", "open", "Run run-value-e04 → Result", "run-value-e04 · p01")])]


LANES = ["Workflow map", "Page Writing", "Evidence", "Supporting Runs"]   # the Page Runs view's own tabs


def run_cards(cx, cy, cw, lane, pills, groups):
    x = cx
    for t in LANES:                                   # the lane tabs, inside the view (no third row)
        w = 24 + 9 * len(t)
        U.base("rectangle", x, cy, w, 30, INK if t == lane else GRAY, 1.5 if t == lane else 1, rough=0)
        U.text(x + 12, cy + 6, t, 14, INK if t == lane else GRAY)
        x += w + 8
    U.path([(cx, cy + 40), (cx + cw, cy + 40)], arrow=False, color=GRAY)
    cy, x = cy + 54, cx
    for k, (label, n) in enumerate(pills):
        w = 14 + 9 * len(f"{n} {label}")
        U.base("rectangle", x, cy, w, 26, GRAY, 1, rough=0)
        U.text(x + 8, cy + 4, f"{n} {label}", 13, INK if k == 0 else GRAY)
        x += w + 8
    y = cy + 44
    for name, runs in groups:
        U.text(cx, y, name, 15, GRAY)
        y += 26
        if not runs:
            U.base("rectangle", cx, y, cw, 36, GRAY, 1, dashed=True, rough=0)
            U.text(cx + 12, y + 9, f"No {name} Run yet.", 13, GRAY)
            y += 48
        for title, state, action, file in runs:
            U.base("rectangle", cx, y, cw, 62, GRAY, 1, rough=0)
            U.text(cx + 12, y + 8, title, 15, INK)
            U.text(cx + 12, y + 34, action, 13, GRAY)
            U.text(cx + cw - 300, y + 34, file, 12, GRAY, MONO)
            U.text(cx + cw - 90, y + 8, "● " + state, 13, GRAY if state == "closed" else INK)
            U.text(cx + cw - 22, y + 18, "›", 20, GRAY)
            y += 70
        y += 8
    return y


def runs_writing(cx, cy, cw):
    y = run_cards(cx, cy, cw, "Page Writing", [("Writing Runs", 4), ("Structure", 1), ("Scratch", 1), ("Sections", 1),
                               ("Paragraphs", 0), ("Revisions", 1)], WRITING)
    return changed(cx, y + 6, ["cards, as today's Page Runs view, not a thin table",
                               "no <MMDD> in a Run's name: one soft Run keeps its passes (p01, p02 …)",
                               "no third row: the lane tabs are the view's own (live in the base)"])


def runs_evidence(cx, cy, cw):
    y = run_cards(cx, cy, cw, "Evidence", [("Evidence Items", 4), ("Displays", 2), ("Citations", 1), ("Values", 1)], EVIDENCE)
    return changed(cx, y + 6, ["one card per evidence item's local Run, grouped by kind"])


def delivery(cx, cy, cw):
    """Delivery: one card per kind of delivery, its state and its result embedded (JL 261007: "each card is
    a type of delivery … the card and the preview of the results, the embedded content"), as the old
    page's Preview did; the paper's Ready group first."""
    U.text(cx, cy, "Ready", 17, INK)
    tag(cx, cy + 2, cw)
    y = U.card(cx, cy + 32, cw, "ready for the build   ✓ outline approved · ✓ every display has preview.pdf · ○ PDF compiles",
               "done: the Page CHECK ○ · the version's submit (G4) is the Job's")
    U.text(cx, y + 10, "Deliveries", 17, INK)
    y += 42
    for title, second, box, h in (
            ("📄 LaTeX   stale", "<page>.tex · <page>-master.tex · <page>.bib ↗", "[ <page>.pdf, embedded ]", 200),
            ("🌐 Web   current", "index.html ↗", "[ the web page, embedded ]", 120),
            ("📝 Word   not built", "not built yet: run Build", None, 0),
            ("🖥 Slides   not built", "not built yet: run Build", None, 0)):
        y = U.card(cx, y, cw, title, second, mark="▾" if box else "▸")
        if box:
            y = U.drawing_box(cx + 20, y - 4, cw - 40, h, box)
    return y


def desc_plan(cx, cy, cw):
    y = U.card(cx, cy, cw, "draft/t03_results-draft-v2.3.md   the plan", "approved ✓ <date> · the first light of 'ready'", mark="▾")
    y = U.table(cx, y + 6, cw, ["part · paragraph", "role", "Bullets"], [0, 380, 640],
                [("C1 · P1", "claim", "B1-B4"), ("C1 · P2", "evidence", "B1-B3"),
                 ("C2 · P1", "contrast", "B1-B5"), ("C2 · P2", "limit", "B1-B2")])
    return U.lines(cx, y + 16, [("owner <person> · reviewer <agent>", GRAY)])


def desc_requirement(cx, cy, cw):
    y = U.table(cx, cy, cw, ["id", "rule", "applies", "source"], [0, 80, 520, 680],
                [("V1", "4-6 paragraphs", "all", "venue §<n> Sec-4-Results"),
                 ("V2", "<n> words at most", "all", "venue"),
                 ("V3", "2 displays at most", "all", "venue"),
                 ("W1", "<the Page's own rule>", "C2", "authored · <date>"),
                 ("W2", "<the Page's own rule>", "C1 · P2", "authored · <date>")], mono=(0,))
    tag(cx, cy - 26, cw)
    y = U.lines(cx, y + 10, [("V-rules are generated from the venue's section; W-rules are written by a person", GRAY)])
    U.text(cx, y + 14, "the draft is judged by: haipipe-writing/base-v1", 17)
    y = U.table(cx, y + 48, cw, ["axis", "asks", "when"], [0, 150, 860],
                [("Mechanics", "the required structure present, ordered, addressable, consistent", "all"),
                 ("Function", "each paragraph answers its reader question and does its job", "all"),
                 ("Evidence", "every claim supported; numbers, citations, uncertainty kept", "all"),
                 ("Readability", "the reader follows without an unstated premise", "all"),
                 ("SUB-RESULT-01", "each Results unit opens with the finding it reports", "G4 ◆"),
                 ("SUB-RESULT-02", "values with N or denominator, and uncertainty", "G4 ◆"),
                 ("SUB-RESULT-03", "observed findings only; mechanism goes to Discussion", "G4 ◆")], mono=(0,), h=30)
    y = U.lines(cx, y + 10, [("verdicts: MEETS · NEEDS WORK · N/A · NOT VERIFIABLE (never a pass) · one row per unit", GRAY),
                             ("used by the writer's self-review and by the independent Page CHECK", GRAY)])
    return changed(cx, y + 6, ["this tab is now haipipe-paper-section's ref/requirement.md (0.11.0)"])


def desc_records(cx, cy, cw):
    y = U.card(cx, cy, cw, "<stem>-context.md   the frozen Context", "the row, the venue's rules and the policy, as CONTEXT froze them")
    y = U.card(cx, y, cw, "<stem>-requirement.md   the rules", "V-rules (generated) · W-rules (authored)")
    return U.card(cx, y, cw, "<stem>-log.md   the Page's log", "one line per step, dated")


def reading(cx, cy, cw):
    U.text(cx, cy, "§3 Results", 20)
    y = U.lines(cx, cy + 40, [("¶1  <sentence one> <sentence two> <sentence three> … [E01]", INK),
                              ("¶2  <sentence one> <sentence two> … [E03]", INK)])
    y = U.drawing_box(cx, y + 6, cw, 150, "[ Display 2 · <title>, in place ]")
    return U.lines(cx, y + 6, [("¶3  <sentence one> <sentence two> … [E04]", INK), ("¶4  …", INK)])


def wd_scratch(cx, cy, cw):
    y = U.card(cx, cy, cw, "Scratch · C2 · P1   a person's rough plan", "open · the AI sums it up when the person closes it", mark="▾")
    y = U.lines(cx + 20, y, [("<rough note: what this paragraph must do>", INK), ("<rough note: the order of its points>", INK)])
    return U.card(cx, y + 10, cw, "Scratch · C1 · P2", "closed <date> · summary: <one line>")


def wd_revise(cx, cy, cw):
    y = cy
    for name in ("C1 · P1", "C1 · P2", "C2 · P1"):
        U.text(cx, y, name, 15, GRAY)
        U.base("rectangle", cx, y + 24, cw, 92, GRAY, 1, rough=0)
        U.lines(cx + 14, y + 34, [("<sentence 1, one per line>", INK), ("<sentence 2>", INK)], gap=26)
        y += 130
    U.base("rectangle", cx, y, 90, 36, INK, 1, rough=0)
    U.text(cx + 22, y + 8, "Save", 16)
    return y + 46


def wd_citation(cx, cy, cw):
    y = U.table(cx, cy, cw, ["item", "source", "state"], [0, 200, 680],
                [("E03-cite", "discovery/…/rNN_<author><year>/", "verified"),
                 ("E05-cite", "discovery/…/rNN_<author><year>/", "verified"),
                 ("E06-cite", "? no deep read yet", "open")], mono=(0, 1))
    return U.lines(cx, y + 16, [("? its keys go to the citation file: three homes today", RED)])


def wd_display(cx, cy, cw):
    y = U.card(cx, cy, cw, "Display1-<slug>   preview.pdf ✓", "results/run-display-<slug>/payload/Display1-<slug>/")
    y = U.card(cx, y, cw, "Display2-<slug>   preview.pdf ✓", "recipe/ · assets/figure.pdf · preview.pdf")
    return U.card(cx, y, cw, "? Display3-<slug>   no recipe, no preview yet", "? migrated as a file only: not ready for the build", red=True)


def wd_value(cx, cy, cw):
    y = U.table(cx, cy, cw, ["item", "as written", "reads", "state"], [0, 160, 340, 700],
                [("E01-value", "<n>%", "work/…/tNN rNN result/<table>.csv", "bound"),
                 ("E02-value", "<n> of <n>", "work/…/tNN rNN result/<table>.csv", "bound"),
                 ("E04-value", "—", "work/…/tNN rNN result/", "open")], mono=(0, 2))
    return U.lines(cx, y + 16, [("the Page rounds and formats; it never computes", GRAY)])


def wd_supporting(cx, cy, cw):
    return U.table(cx, cy, cw, ["Supporting Run", "kind", "feeds"], [0, 520, 720],
                   [("work/…/tNN_<task>/runs/rNN_<run>", "hard · work", "E01 · E02"),
                    ("work/…/tNN_<task>/runs/rNN_<run>", "hard · work", "E04"),
                    ("discovery/…/rNN_<author><year>", "hard · discovery", "E03 · E05")], mono=(0,))


DESC = ["Scope", "Plan", "Requirement", "Records"]
AUD = ["Table", "Reading", "Questions", "Comments"]
WD = ["Draft-Scratch", "Draft-Revise", "Evidence-Citation", "Evidence-Display", "Evidence-Value", "Supporting"]
DRAFT = "t03_results/draft/t03_results-draft-v<G>.<S>.md"
READ_ONLY = "read only: its content is\nchanged by the Runs in\nWork Details"   # JL 261007: the Audience Report is for reading

# one row per Space: (Space, its third row, its run types, [(view, body, on disk)], what it is, on the right)
ROWS = [
    ("Description", DESC, ["Context"], [
        ("Scope", description, [("t03_results/t03_results.md", "the face: its header is the reader contract"),
                                ("paper/venue/bank/1-QBv-desks/QBv<n>-<desk>/", "structure-source: the venue's section"),
                                ("j02_v<MMDD>_<desk>/j02_v<MMDD>_<desk>.md  ## Narrative", "its row: the story-row (s12)")]),
        ("Plan", desc_plan, [(DRAFT, "the plan: parts, paragraphs, Bullets"),
                             ("t03_results/runs/run-structure-<slug>.md", "the Run that shapes it")]),
        ("Requirement", desc_requirement, [("t03_results/draft/records/<stem>-requirement.md", "V-rules · W-rules"),
                                           ("paper/venue/bank/1-QBv-desks/QBv<n>-<desk>/", "where the V-rules come from"),
                                           ("haipipe-paper-section/ref/requirement.md", "V · W · the rubric · SUB-* (0.11.0)"),
                                           ("haipipe-writing/ref/evaluation-rubric.md", "the base rubric: 4 axes, 4 verdicts"),
                                           ("haipipe-paper/ref/submission-readiness.md", "the Section's SUB-* rows (G4)")]),
        ("Records", desc_records, [("t03_results/draft/records/<stem>-context.md", "the frozen Context"),
                                   ("t03_results/draft/records/<stem>-requirement.md", "the rules"),
                                   ("t03_results/draft/records/<stem>-log.md", "the log")])],
     [("h", "Description · the Section's face and its rules"),
      ("◆", "Scope: the reader contract, read from the face's header: the reader's question, what they know "
            "coming in and leaving, what must be established and refused, the joins to the Sections around it, "
            "its Story row. A stale row sends the Section back to its Story (HOLD)."),
      ("t", "Plan: the versioned outline, parts → paragraphs → Bullets, one role each; a person approves it."),
      ("◆", "Requirement: the venue's rules (V, generated from its section in the venue bank) and the Page's "
            "own (W, written by a person), then the rubric the draft is judged by: the four axes (Mechanics, "
            "Function, Evidence, Readability), and at submission the Section's SUB-* rows."),
      ("t", "Records: what CONTEXT froze, the rules, and the Page's log."),
      ("t", "runs: Context"),
      ("t", "Decided (JL 261007): Requirement is its own tab; today it is a lens in the Outline.")]),
    ("Idea Studio", None, ["Draw the logic", "Redraw the Section map"], [
        (None, studio, [("t03_results/studio/s01-logic/s01-logic.excalidraw", "the person's"),
                        ("t03_results/studio/s02-section-map/", "generated by excalidraw-section")])],
     [("h", "Idea Studio · the Section's logic, drawn"),
      ("t", "One drawing per topic: the logic by hand (the claim left, its reasons beside it, every Bullet a "
            "row), then the Section map, generated by excalidraw-section, view only."),
      ("t", "runs: Draw the logic · Redraw the Section map"),
      ("t", "Decided (JL 261007): a Section has its own studio/ and reports/, as every Task; one sNN-<topic>/ "
            "folder per drawing; both start empty and fill as the drawings are made.")]),
    ("Audience Report", AUD, [], [
        ("Table", table, [(DRAFT, "## 1 Structure: paragraphs, Bullets, their Draft"),
                          ], [], READ_ONLY),
        ("Reading", reading, [(DRAFT, "each Bullet's Draft, in order"),
                              ("t03_results/results/run-display-…/payload/", "the displays, in place")], [], READ_ONLY),
        ("Questions", questions, [("t03_results/t03_results.md  ## Questions", "the register: one row per question"),
                                  ("t03_results/reports/qNN_<topic>/qNN_<topic>.md", "its report: answers · answer-status"),
                                  ("t03_results/results/<run>/v<NNN>.md", "today: (+) notes, inside a Run's journal")],
         ["Ask a question", "Write the report"]),
        ("Comments", reviews, [("<version>/reports/qNN_<kind>-<MMDD>/", "a report of type comments: its ## Review Items"),
                              ("t03_results/runs/run-revise-<slug>.md", "the Run named for its item"),
                              ("<version Job>/delivery/sent/<date>/", "the passage as sent")], [], READ_ONLY)],
     [("h", "Audience Report · what the reader gets"),
      ("t", "Table: today's Draft table: one row per paragraph, then its Bullets (address, role, statement, "
            "evidence) beside the Draft written from each; a paragraph's (+) holds its notes."),
      ("t", "Reading: the prose as the reader reads it, with the displays in place."),
      ("t", "Questions (JL 261007): the discussion questions kept while the Section is changed. Each is a row "
            "in the face's ## Questions and a report in reports/qNN_<topic>/ (Answer · Evidence · Limits · "
            "Next), as a Block's Questions are; the answer names what it changed in the draft."),
      ("✎", "A comments batch is a report of type comments in the version, <version>/reports/qNN_<kind>-<MMDD>/ (JL 261007), never a Task."),
      ("t", "Comments (JL 261007; was Reviews): the Review Items of the version's comments reports (review, editor, coauthor, meeting, advisor) that land on this Section, Review-<slug> citing "
            "the points it answers (R1.1, E1.2, A1.2), in the Round's states (open · routed · applied · answered · "
            "declined · deferred); each opens the item: "
            "the words, the passage as sent beside it now, the Run, the reply. It is answered by Revise edits "
            "(run-revise-<slug>) in Work Details › Draft-Revise."),
      ("t", "For reading (JL 261007): a person reads here; skills and agents change the content through the "
            "Runs in Work Details (Structure, Section and Paragraph revise move there). Only Questions has run "
            "types: Ask a question · Write the report.")]),
    ("Work Details", WD, [], [
        ("Draft-Scratch", wd_scratch, [(DRAFT, "the Scratch registry"),
                                       ("t03_results/runs/<name>.md · results/<name>/", "its ticket and its journal")],
         ["Scratch", "Structure revise", "Evidence embed"]),
        ("Draft-Revise", wd_revise, [(DRAFT, "Save writes each line back to its Bullet's Draft")],
         ["Section revise", "Paragraph revise", "Revise edits", "Auto write"]),
        ("Evidence-Citation", wd_citation, [("t03_results/draft/<stem>-evidence-items.md", "the cite items"),
                                            ("t03_results/delivery/latex/draft-bibliography/<page>.bib", "its citations, today"),
                                            ("? <stem>.bib · selected-bibliography/<page>.bib", "? the other two homes")],
         ["Bind / update citation"]),
        ("Evidence-Display", wd_display, [("t03_results/results/run-display-…/payload/Display<n>-<slug>/", "one display unit"),
                                          ("    recipe/ · assets/ · preview.pdf", "its script, figure, preview")],
         ["Build figure / table"]),
        ("Evidence-Value", wd_value, [("t03_results/draft/<stem>-evidence-items.md", "the value items"),
                                      ("t03_results/results/run-value-<slug>/", "a value's local Run")],
         ["Bind / update value"]),
        ("Supporting", wd_supporting, [("work/… · discovery/…", "their own Tasks: kept at their path, never copied")],
         ["Task runs", "Discovery runs"])],
     [("h", "Work Details · how the Section is made"),
      ("t", "Draft-Scratch: a person's rough plan for one target; the AI sums it up on close."),
      ("t", "Draft-Revise: one box per paragraph, its Draft pre-filled; Save writes back to the Bullets. "
            "A person edits by hand here, or calls a revise Run."),
      ("t", "Evidence-Citation · Display · Value: each item bound to the Result it came from."),
      ("t", "Supporting (b03's Evidence-Supporting Runs, short so the row fits): the hard work and discovery Runs "
            "the items read."),
      ("t", "A Page computes no new number: it reads finished hard Results."),
      ("t", "Each view has its own run types, as today's Draft views do. Draft-Scratch: Scratch · Structure "
            "revise · Evidence embed. Draft-Revise: Section revise · Paragraph revise · Revise edits · Auto write. "
            "Evidence-…: Bind / update citation · Build figure / table · Bind / update value. Supporting: Task "
            "runs · Discovery runs."),
      ("?", "The citation file has three homes: <stem>.bib (b03), selected-bibliography/ (the skill), "
            "delivery/latex/draft-bibliography/ (on disk). Which one?")]),
    ("Runs", None, ["Run"], [
        ("Page Writing", runs_writing, [("t03_results/runs/run-<type>-<slug>.md", "a soft Run: one file, its passes inside"),
                                        ("t03_results/results/run-<type>-<slug>/", "its Result: payload/ · result.yaml · runtime.yaml")]),
        ("Evidence", runs_evidence, [("t03_results/runs/run-display-<slug>.md", "an evidence item's local Run"),
                                     ("t03_results/results/run-display-<slug>/payload/Display<n>-<slug>/", "its Result")])],
     [("h", "Runs · the Section's soft Runs"),
      ("t", "The Page's own Runs view, embedded: its lane tabs (Workflow map · Page Writing · Evidence · "
            "Supporting Runs), count pills, then one group per kind, each Run a card: its name, its state, what "
            "it does; › opens its Result. No third row; run type: Run."),
      ("✎", "Live in the base frame (b03): the Runs Space of every Page Task embeds this view."),
      ("t", "A soft Run is one file, runs/<name>.md; its Result is results/<name>/. No hard rNN_ Run sits in a "
            "Section: the facts come from the work and discovery Tasks."),
      ("✎", "Cards in place of the thin Run │ type │ state table, which left most of the screen empty."),
      ("✎", "No <MMDD> in a Run's name: a soft Run is worked in passes (p01, p02 …) inside the one file, so "
            "the date says nothing the passes don't. run-<type>-<slug> (JL 261007)."),
      ("✎", "Renamed (JL 261007: \"rename them\"): the page engine now names run-<kind>-<slug> and still reads a dated "
            "name; page.py run-names dropped the day on 9 Sections. 7 wait: their built LaTeX points at the dated "
            "display folders, so they rename with their delivery rebuild."),
      ("?", "Or a folder per Run, runs/run-<type>-<target>/, as the ladder says?")]),
    ("Delivery", None, ["Build", "Check"], [
        (None, delivery, [("t03_results/delivery/latex/<page>.pdf", "the LaTeX card's preview"),
                          ("t03_results/delivery/web/index.html", "the Web card's preview"),
                          ("t03_results/delivery/word/<page>.pdf", "the Word card's preview: the .docx's PDF twin"),
                          ("t03_results/delivery/slides/<page>-deck.html", "the Slides card's preview"),
                          ("<version Job>/delivery/latex/", "where the version uses the piece")])],
     [("h", "Delivery · what leaves the Section"),
      ("◆", "Ready for the build: the outline approved, every display with its preview.pdf, its PDF compiles. "
            "Done is separate: the Page CHECK. Submitting is the version's (G4)."),
      ("t", "One card per kind of delivery, no third row (JL 261007): Web · LaTeX · Word · Slides · Render. Each "
            "card: its state from the Page's own check (current · stale · not built), its files as small links, "
            "and its result embedded: the PDF, the web page, Word through the PDF twin the build draws, the deck. "
            "A LaTeX card with no PDF yet shows the .tex."),
      ("t", "LaTeX: <page>-master.tex builds the Section's own PDF; <page>.tex is the piece the version pulls in."),
      ("t", "All generated: a fix goes into the Page, then it is rebuilt."),
      ("t", "runs: Build · Check")]),
]
GUIDE_ROW = U.guide_method("Task")
GUIDE_ABOUT = [("h", "Guide › Method, opened from this tab"),
               ("t", "The Task section open: the Page method's steps and cards; Block and Job folded."),
               ("?", "The Task steps in the paper's words are proposed in s31 (the paper Guide).")]

ROW_GAP, VIEW_GAP, ABOUT_W = 260, 120, 900


def about(x, y, items):
    """The Space explained, on the right of its row: a heading, then lines (◆ paper adds, ? open = red)."""
    for kind, s in items:
        if kind == "h":
            U.text(x, y, s, 24)
            y += 50
            continue
        color = {"◆": TEAL, "?": RED, "✎": GREEN}.get(kind, INK)
        lead = {"◆": "◆ ", "?": "? ", "✎": "✎ 261007  "}.get(kind, "")
        for k, line in enumerate(U.wrap(lead + s, 70)):
            U.text(x, y + k * 28, line, 18, color)
        y += len(U.wrap(lead + s, 70)) * 28 + 18
    return y


def level_rows(out):
    """One row per Space (JL 261007: "make each space to be a row"): its views side by side, each a full
    screen with "on disk" under it, and the Space explained on the right; one frame per row."""
    L = U.L
    L.els.clear()
    L.FRAME[0] = None
    fr = L.open_frame("Task level · today → proposed")
    U.text(0, 0, "Task level: a paper Section, a Page Task with the paper's few additions", 34)
    U.text(0, 50, "One row per Space: its views side by side, each a full screen with its files under it; the Space "
                  "explained on the right. ◆ = what the paper adds; red = proposed or open; green ✎ = a change, dated. Placeholders only.", 20, GRAY)
    for k, (a, b) in enumerate(MOVES):
        U.text(0, 120 + k * 32, a, 17, GRAY)
        U.text(460, 120 + k * 32, "→  " + b, 17, RED if "?" in b else INK)
    changed(0, 120 + len(MOVES) * 32 + 16, ["a Section is now named t0N_<title>/ (t2N_ appendix); the version renamed them (s12)",
                                            "a comments batch is not a Task; t3N_ is Letters (t31 cover letter, t32 response)",
                                            "a comments batch is a report of type comments: <version>/reports/qNN_<kind>-<MMDD>/, a row in ## Questions (group comments)",
                                            "a Section's story-row comes from the version face's ## Narrative (the Story is now studio/ topics)",
                                            "dated Runs renamed by page.py run-names: 9 Sections now; 7 after their delivery rebuild",
                                            "no <MMDD> in a Run's name: run-<type>-<slug>, its passes inside"])
    L.close_frame(fr)
    y = fr["y"] + fr["height"] + 300
    rows = [(sp, thr, rt, views, ab, False) for sp, thr, rt, views, ab in ROWS]
    g = GUIDE_ROW
    rows.append(("Guide › Method", None, g[2], [(None, g[4], g[5])], GUIDE_ABOUT, True))
    for i, (space, thr, run_types, views, ab, guide) in enumerate(rows):
        name = f"{i + 1:02d} · " + (space if guide else f"Task tab › {space}")
        fr = L.open_frame(name)
        U.text(0, y, name, 32)
        x, top = 0, y + 70
        for view, body, files, *own in views:
            rt, note = (own[0], own[1] if len(own) > 1 else "") if own else (run_types, "")
            head = ("Guide › Method, from the Task tab" if guide else
                    f"Task tab › {space}" + (f" › {view}" if view and (not thr or len(thr) > 1) else ""))
            U.text(x, top, head, 22)
            space_on = "Method" if guide else space
            body(*U.screen(x, top + 40, "Task", space_on, U.third(thr, view) if thr else None, rt, note, guide))
            U.files(x, top + 40 + U.SH + 50, files)
            x += U.SW + VIEW_GAP
        about(x + 40, top + 40, ab)
        L.close_frame(fr, pad=40)
        y = max(e["y"] + e.get("height", 0) for e in L.els) + ROW_GAP
    fr = L.open_frame("pop-outs")
    U.text(0, y, "pop-out, from a ↗", 24)
    px = 0
    for t, rws in POPOUTS:
        U.window(px, y + 40, 900, t, rws)
        px += 960
    L.close_frame(fr, pad=40)
    bottom = max(e["y"] + e.get("height", 0) for e in L.els)
    fr = L.open_frame("open ?")
    U.scratch_questions(0, bottom + 260, QUESTIONS)
    L.close_frame(fr, pad=50)
    U.canvas.write(out, list(L.els), "build_s13_paper_task.py")


POPOUTS = [("Review-<slug-a>  ·  a Review Item", [
    ("cites R1.1 · R2.3 · lands on t03_results ¶2 · C2 · applied", INK),
    ("[ the reviewers' words, in full ]", GRAY),
    ("as sent (delivery/sent/<date>/)  │  now (the Run's before / after)", INK),
    ("Run: run-revise-<slug-a> · ¶2 changed", INK),
    ("reply: P3 in the Round's Response Package", INK)]),
    ("q01_<topic>  ·  a Section's question report", [
    ("reports/q01_<topic>/q01_<topic>.md", GRAY),
    ("answers: Q01 · answer-status: answered", INK, ),
    ("Answer   <one paragraph>", INK),
    ("Evidence   the draft before · after, the Run that changed it", INK),
    ("Limits · Next   <what it leaves open>", INK),
    ("changed: C1.P2 → C2.P1 · run-section-<slug> v3", INK)]),
    ("E04-value  ·  an evidence item", [
    ("draft/t03_results-evidence-items.md › E04", GRAY),
    ("need: <the number this Bullet states>", INK),
    ("reads: work/…/tNN rNN result/<table>.csv (a hard Result)", INK),
    ("local Run: run-value-e04 · state open", INK),
    ("frozen input before LAND; the Page rounds and formats, never computes", GRAY)]),
    ("t03_results in j02's Narrative", [
        ("#3 of 5 · carries C1 · C2 · released (G3) ✓", INK),
        ("before: t02_method · after: t04_discussion", INK),
        ("the claim's warrant: in the Story, now studio/sNN-story-<telling>/", GRAY),
        ("✎ 261007  read from the version face's ## Narrative (the Story Page's §8 moved there)", GREEN)]),
    ("qNN_<kind>-<MMDD>  ·  a comments batch: a report of type comments", [
        ("<version>/reports/qNN_<kind>-<MMDD>/  qNN_….md · page-type: comments · its ## Review Items", INK),
        ("✎ 261007  a report of type comments, a row in ## Questions (group comments); never a Task", GREEN),
        ("  feedback/   the reviews and the editor's letter, as received", INK),
        ("  meeting/    the team's brief on them", INK),
        ("  sent/       the frozen copy that was sent", INK),
        ("✎ 261007  was a t3N_ Task; t3N_ is now Letters (t31 cover letter, t32 response)", GREEN)])]

QUESTIONS = ["? Questions › Work: the Runs that worked it (drawn) or the answering Jobs and Tasks (live today)",
             "? The citation file has three homes: <stem>.bib (b03), selected-bibliography/ (the skill), "
             "delivery/latex/draft-bibliography/ (on disk). Which one",
             "? A Section's question that outgrows it (the claim itself): does its report move to the Block's reports/",
             "? A soft Run: one file runs/<name>.md + results/<name>/ (today), or a folder runs/run-<type>-<target>/",
             "? The Page method's 'By reader expectations' card and the paper's Writing card of the same name: keep one",
             "? The version's Narrative row: a line in Scope (drawn), or its own Description group",
             "? Round and Letter Tasks: their own six Spaces (with Q03)"]

if __name__ == "__main__":
    level_rows(Path(sys.argv[1]) if len(sys.argv) > 1 else HERE / "s13-paper-task.excalidraw")
