#!/usr/bin/env python3
"""Build a paper's shippable `displays/` tree from its display stage's `display/`.

WHY THIS EXISTS. `displays/` used to BE the source: it held candidates, versions,
source recipes and previews, which is working machinery, while sitting in the
paper's unnumbered deliverable space. The paper-folder rule is the delete test,
`0-lifecycle 1-probes 2-src` are machinery and everything unnumbered is the
deliverable, so the machinery moved into `0-lifecycle/S05-display/display/` and
`displays/` became a build target. It is now to the display layer exactly what
`sections/` is to the manuscript layer: generated, committed, and never edited
by hand.

WHAT IT SHIPS. Per unit, only the two things LaTeX needs:

    displays/<unit>/float.tex     the table/figure env, caption and notes
    displays/<unit>/assets/*      the SELECTED artifact it points at

Not candidates, not versions, not source recipes, not previews. A journal tex
tree has to be self-contained and cannot reach into `0-lifecycle/`, which is why
this COPIES the asset rather than pointing back at the workspace.

WHAT IT REWRITES. A workspace `float.tex` points at its own workspace assets so
that `preview.tex` builds from the paper root against the source of truth. The
shipped copy has to point inside `displays/`, so every occurrence of the
workspace prefix is rewritten on the way out. That rewrite is the whole reason
this is a build and not a copy.

    python3 <skill>/cli/build-displays.py <stage-dir>            build
    python3 <skill>/cli/build-displays.py <stage-dir> --check    non-zero exit if stale

The stage directory defaults to the working directory, so the old habit of
running it from inside the stage still works. `src/display_unit.py` holds the anchor
rules and says why they are arguments rather than `__file__`.
"""
import hashlib
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from src import display_unit as _stage                            # noqa: E402

STAGE = _stage.stage_dir()
ROOT = _stage.paper_root(STAGE)
WS = _stage.authoring_dir(STAGE)
WS_REL = _stage.rel(WS, ROOT)
OUT = ROOT / "displays"
OUT_REL = "displays"

# The tool no longer lives in the tree it builds, so the banner names the tool
# by its skill path and the source by its paper-relative one. Both used to be
# spelled from `__file__` and both went stale the moment a folder was renamed:
# an earlier literal named `0-lifecycle/3-display/`, a directory that had not
# existed for weeks, which is the one line a reader trusts about where the real
# file lives.
BANNER = (
    f"%% GENERATED by board/haipipe-board/cli/{Path(__file__).name} from\n"
    "%%   {src}\n"
    f"%% Do not edit this file. Edit the copy under {{ws}}/ and rebuild.\n"
)

UNITS = _stage.units(WS)


def units():
    """Every unit in the authoring folder, in reading order."""
    return UNITS


def shipped_float(unit):
    """The authoring float.tex with its asset paths repointed into displays/."""
    text = (unit / "float.tex").read_text(encoding="utf-8")
    # Rewrite EVERY unit's authoring prefix, not just this unit's: a float may
    # legitimately reference a sibling's asset, and a half-rewritten path would
    # resolve on this machine and nowhere else.
    for other in units():
        text = text.replace(f"{WS_REL}/{other.name}/",
                            f"{OUT_REL}/{other.name}/")
    return BANNER.format(src=f"{WS_REL}/{unit.name}/float.tex", ws=WS_REL) + text


def plan(unit):
    """-> {relative shipped path: bytes} for one unit."""
    out = {f"{unit.name}/float.tex": shipped_float(unit).encode("utf-8")}
    assets = unit / "assets"
    if assets.is_dir():
        for a in sorted(assets.iterdir()):
            # README.md in assets/ is the provenance manifest, which belongs to
            # the workspace. Shipping it would put a second hash record in the
            # deliverable, disagreeing with the workspace one the moment either
            # side moves.
            if not a.is_file() or a.name == "README.md" or a.name.startswith("."):
                continue
            out[f"{unit.name}/assets/{a.name}"] = a.read_bytes()
    return out


def build(check_only=False):
    want = {}
    for u in units():
        want.update(plan(u))

    have = {}
    if OUT.is_dir():
        for p in OUT.rglob("*"):
            # `_old/` is a legacy parking area this build does not own.
            if p.is_file() and "_old" not in p.relative_to(OUT).parts:
                have[str(p.relative_to(OUT))] = p.read_bytes()

    added = sorted(set(want) - set(have))
    removed = sorted(set(have) - set(want))
    changed = sorted(k for k in set(want) & set(have) if want[k] != have[k])

    if check_only:
        for tag, rows in (("+", added), ("~", changed), ("-", removed)):
            for r in rows:
                print(f" {tag} {OUT_REL}/{r}")
        if added or removed or changed:
            print(f"\n❌ STALE: {len(added)} added, {len(changed)} changed, "
                  f"{len(removed)} removed. Run without --check.")
            return 1
        print(f"✅ {OUT_REL}/ matches the workspace ({len(want)} files, "
              f"{len(units())} units).")
        return 0

    for r in removed:
        (OUT / r).unlink()
    for r, blob in want.items():
        p = OUT / r
        p.parent.mkdir(parents=True, exist_ok=True)
        if not p.is_file() or p.read_bytes() != blob:
            p.write_bytes(blob)
    for u in units():
        h = hashlib.sha256(want[f"{u.name}/float.tex"]).hexdigest()[:16]
        n = sum(1 for k in want if k.startswith(f"{u.name}/assets/"))
        print(f"  {u.name:<44} float {h}  ·  {n} asset(s)")
    print(f"\n✅ built {OUT_REL}/ from {WS_REL}/ "
          f"({len(units())} units, {len(want)} files"
          f"{f', {len(removed)} removed' if removed else ''})")
    return 0


BEGIN = "# --- display-map:begin (generated) ---"
END = "# --- display-map:end ---"


def _master_closure():
    r"""Every .tex LaTeX actually opens, from the master's \input tree."""
    masters = [p for p in sorted(ROOT.glob("*.tex"))
               if re.search(r"^\s*\\begin\{document\}",
                            p.read_text(encoding="utf-8", errors="replace"), re.M)]
    seen, queue = set(), list(masters)
    while queue:
        p = queue.pop()
        if not p.is_file() or p.resolve() in seen:
            continue
        seen.add(p.resolve())
        for m in re.finditer(r"^[^%\n]*\\(?:input|include)\{([^}]+)\}",
                             p.read_text(encoding="utf-8", errors="replace"), re.M):
            for c in (ROOT / m.group(1), ROOT / (m.group(1) + ".tex")):
                if c.is_file():
                    queue.append(c)
                    break
    return seen


def display_map():
    r"""The unit-to-label map, DERIVED from the only two authorities.

    WHY GENERATED AND NEVER AUTHORED. A hand-written map is a third place that
    claims to know the truth, and this repo has been burned by that shape twice:
    `STATUS.md` was retired on 2026-07-26 for holding a frontier that could only
    go stale, and the 260727 renumber damaged its own mapping table badly enough
    that the rule was written down, a mapping table is the one shape a global id
    rewrite must never touch. Both sides of this map already exist on disk. The
    unit is its folder name, which is also its page name. The label is the
    `\label{}` inside that unit's `float.tex`. Nothing else declares either, so
    nothing else should restate them.
    """
    printed = _master_closure()
    rows, owned = [], {}
    for u in units():
        ft = (u / "float.tex").read_text(encoding="utf-8")
        kind = (re.search(r"\\begin\{(table|figure)\*?\}", ft) or [None, "?"])[1]
        lab = (re.search(r"\\label\{([^}]*)\}", ft) or [None, ""])[1]
        built = OUT / u.name / "float.tex"
        rows.append((u.name, "tab" if kind == "table" else "fig", lab,
                     "yes" if built.resolve() in printed else "NO -> ??"))
        if lab:
            owned[lab] = u.name

    # A label the paper declares that NO unit owns. This is the shape that let
    # `tab:main_results` paint green out of a retired `_old/` file.
    stray = {}
    for p in sorted(ROOT.rglob("*.tex")):
        if {"_archive", ".claude"} & set(p.parts):
            continue
        if p.is_relative_to(WS) or p.is_relative_to(OUT / "S-Display-x"):
            continue
        for m in re.finditer(r"\\label\{((?:tab|fig):[^}]*)\}", p.read_text(
                encoding="utf-8", errors="replace")):
            lab = m.group(1)
            if lab not in owned and not p.is_relative_to(OUT):
                stray.setdefault(lab, p.relative_to(ROOT).as_posix())

    w = max(len(r[0]) for r in rows)
    out = [BEGIN,
           "  ONE UNIT, ONE LABEL. Generated by board/haipipe-board/cli/build-displays.py.",
           "  Do not hand-edit: the unit is its folder name, which is also its page name,",
           "  and the label is the \\label{} inside that unit's float.tex. Nothing else",
           "  declares either, so nothing else should restate them.",
           "",
           "  WHICH NAME TO WRITE, in a markdown page:",
           "    talking ABOUT the display  ->  the UNIT name, which renders as the evidence card",
           "    pointing FROM a sentence   ->  \\ref{tab:...}, because that line becomes manuscript",
           "  A `> Display:` lane writes BOTH, unit first, then the pointer it binds.",
           "",
           f"  {'unit':<{w}}  kind  {'label':<32} reaches master",
           f"  {'-' * w}  ----  {'-' * 32} --------------"]
    for name, kind, lab, reach in rows:
        out.append(f"  {name:<{w}}  {kind:<4}  {lab or '(none)':<32} {reach}")
    if stray:
        out += ["", "  UNOWNED LABELS, declared by the paper and by no unit:"]
        for lab, where in sorted(stray.items()):
            out.append(f"    {lab:<34} {where}")
    out.append(END)
    return "\n".join(out)


def write_map():
    p = WS / "README.md"
    text = p.read_text(encoding="utf-8")
    block = display_map()
    if BEGIN in text and END in text:
        head, rest = text.split(BEGIN, 1)
        text = head + block + rest.split(END, 1)[1]
    else:
        text = text.rstrip() + "\n\n## The unit-to-label map\n\n```\n" + block + "\n```\n"
    p.write_text(text, encoding="utf-8")
    return block


if __name__ == "__main__":
    if "--map" in sys.argv:
        print(write_map())
        sys.exit(0)
    rc = build(check_only="--check" in sys.argv)
    if rc == 0 and "--check" not in sys.argv:
        write_map()
        print(f"  map written to {WS_REL}/README.md")
    sys.exit(rc)
