"""
Generate one folder per example category, each holding the EXACT request and the
EXACT response, so a consumer can see what the API does without running it.

    source .venv/bin/activate && source env.sh
    python Tools/plugins/haipipe-utils/skills/describe-exercise/examples/run_examples.py

Every case writes:
    request.json   the body that was POSTed
    curl.sh        the same call, runnable from inside the case folder
    response.json  what came back, verbatim
    NOTE.md        what this case is showing and why it matters

Nothing here is hand-written. Re-run after any resolver change; a diff in
response.json IS the behaviour change.

Group 8 is different from the rest and is the important one: every case there is
one ACTUAL ROW from 1-SourceStore, picked by running all 136,555 of them through
this service. Groups 1-7 illustrate the contract with clean inputs; group 8
shows what the contract does to the data we really have, including the row that
claims a 78-hour walk.
"""
import json
import os
import pathlib
import subprocess
import sys
import urllib.request

URL = os.environ.get("EXNORM_URL", "http://127.0.0.1:8078").rstrip("/")
HERE = pathlib.Path(__file__).resolve().parent
OUT = HERE / "api"

README_HEAD = """# describe-exercise — worked API examples

GENERATED by `run_examples.py`. Do not hand-edit; re-run it instead.

Each folder is one real call against the live service: the request that went
out, the response that came back, and a note saying what the case is for. A
change in any `response.json` is a change in behaviour.

    cd api/<case> && bash curl.sh

"""

CASES = [
    # ---- 1. the ordinary path ------------------------------------------
    ("1-resolves/walk-30min", "a named activity with minutes and body mass",
     "/normalize", {"activity": "Walking", "minutes": 30, "weight_kg": 82},
     "The whole point, in one call. A logged noun becomes a compendium entry, a "
     "MET, and a kcal, and every one of those carries where it came from."),
    ("1-resolves/yoga-45min", "a low-MET activity",
     "/normalize", {"activity": "Yoga_Pilates", "minutes": 45, "weight_kg": 70},
     "The cohort spelling 'Yoga_Pilates' folds to 'yoga' in the dialect layer "
     "before the bank ever sees it. Note MET 2.3: 45 minutes of Hatha yoga is "
     "not 45 minutes of running, and the estimate says so."),
    ("1-resolves/batch-mixed", "one batch, five cohort spellings",
     "/normalize/batch", {"activities": ["Walk", "Bicycling", "Running",
                                         "Strength_training", "Gardening__Lawn"],
                          "minutes": [25, 40, 20, 35, 60], "weight_kg": 78},
     "How a SourceFn actually calls it: the distinct strings, in one request, "
     "answers in the same order."),

    # ---- 2. the basis, which is the whole discipline --------------------
    ("2-basis/both-known", "minutes AND mass -> per_session",
     "/normalize", {"activity": "Walking", "minutes": 30, "weight_kg": 82},
     "ExerciseBasis 'per_session'. A kcal is only issued when both denominators "
     "were stated."),
    ("2-basis/no-weight", "minutes only -> per_minute",
     "/normalize", {"activity": "Walking", "minutes": 30},
     "Same activity, same MET, NO kcal. There is no default body mass, because "
     "a default body mass is a fabricated number wearing a plausible value."),
    ("2-basis/no-minutes", "mass only -> per_minute",
     "/normalize", {"activity": "Walking", "weight_kg": 82},
     "MET is a RATE. Without minutes there is no dose to report, and the basis "
     "column says which of the two you are holding."),
    ("2-basis/duration-zero", "ExerciseDuration 0 is not a bout of zero length",
     "/normalize", {"activity": "Walking", "minutes": 0, "weight_kg": 82},
     "57,419 rows in 1-SourceStore carry duration 0. That is a duration that "
     "was never stated, not a workout that lasted no time."),

    # ---- 3. the roll-ups: 64.7% of every exercise row -------------------
    ("3-rollups/daily-minutes", "code 20903 under EntrySourceID 20",
     "/normalize", {"activity": "20903", "source_id": 20, "minutes": 11,
                    "weight_kg": 82},
     "33,617 rows. One per patient per DAY, always at local midnight, "
     "CaloriesBurned always 0. It is a device's daily summary, not a bout. "
     "Pricing it as one says a patient did a single 11-minute workout every day "
     "for four years and never burned a calorie."),
    ("3-rollups/daily-distance", "code 20905, distance-only",
     "/normalize", {"activity": "20905", "source_id": 20, "minutes": 0},
     "53,949 rows, the single largest group in the whole table. Same shape."),
    ("3-rollups/namespace-matters", "the same digits from another vendor",
     "/normalize/batch", {"activities": ["20903", "20903"],
                          "source_ids": [20, 37], "minutes": 11},
     "Identical strings, different verdicts. '20903' is a roll-up because "
     "EntrySourceID 20 issued it; the same digits from source 37 are a "
     "different vendor's code and do not inherit that."),

    # ---- 4. the collision this package exists to prevent ----------------
    ("4-collision/church-supper", "WellDoc 20050 is NOT compendium 20050",
     "/normalize/batch", {"activities": ["20050", "20037", "20020"],
                          "source_ids": 20, "minutes": 42, "weight_kg": 80},
     "All three codes exist in BOTH code spaces, by coincidence. The PA "
     "Compendium calls 20050 'Eating at church', MET 1.5. WellDoc's 20050 has a "
     "median 42 minutes and 242 kcal. Joining on the bare integer would price "
     "1,218 real workouts as a church supper, so the join is refused outright."),

    # ---- 5. honest failures, four of them, kept separate ----------------
    ("5-misses/opaque-code", "a vendor code with no codebook here",
     "/normalize", {"activity": "1001", "source_id": 23, "minutes": 21},
     "10,856 rows. A KNOWN unknown: somebody has this codebook, just not this "
     "machine. Deliberately NOT the same source string as a bank miss."),
    ("5-misses/named-nothing", "'Unknown' names no activity",
     "/normalize", {"activity": "Unknown", "minutes": 30, "weight_kg": 80},
     "Typed as a placeholder, not dropped. Dropping it would make the cohort "
     "read as a bank failure when the log simply never named anything."),
    ("5-misses/category-word", "'Sports' is a category, not an activity",
     "/normalize", {"activity": "Sports", "minutes": 30, "weight_kg": 80},
     "714 rows. It head-anchors at a perfect score onto 'Sports spectator, very "
     "excited', MET 3.3 -- and a patient who logged Sports was not watching "
     "one. WEAK: the candidate rides along so a person can curate it, the "
     "number does not."),
    ("5-misses/not-in-bank", "a string the compendium has never heard of",
     "/normalize", {"activity": "quidditch", "minutes": 30, "weight_kg": 80},
     "The fourth distinct failure. Four kinds of not-knowing, four different "
     "ExerciseSource strings, because they have four different fixes."),

    # ---- 6. caller errors -----------------------------------------------
    ("6-errors/length-mismatch", "minutes shorter than activities",
     "/normalize/batch", {"activities": ["Walking", "Yoga"], "minutes": [30]},
     "422, not a silent zip truncation. Truncating would re-pair every row "
     "after the missing one onto the wrong activity, with no exception raised."),
    ("6-errors/bad-number", "minutes that is not a number",
     "/normalize/batch", {"activities": ["Walking"], "minutes": "abc"},
     "422. A NaN means the log stated no duration; the string 'abc' means the "
     "caller has a bug. They used to share a return value."),
    # ---- 7. the code books --------------------------------------------
    ("7-codebooks/four-dialects", "one activity, four dialects, one MET",
     "/normalize/batch", {"activities": ["Walk", "20052", "1001", "100"],
                          "source_ids": [None, 20, 23, 1],
                          "minutes": 30, "weight_kg": 82},
     "A patient typed 'Walk'. Apple called it 52. Validic called it 1001. The "
     "WellDoc app called it 100. All four reach compendium 17190 and MET 3.8 "
     "through ONE curated pick -- and each keeps its own TypeSource, because a "
     "name a patient typed is not the same evidence as a name read off an enum."),
    ("7-codebooks/apple-prefix", "Apple codes are '20' + HKWorkoutActivityType",
     "/normalize/batch", {"activities": ["20052", "20037", "20013", "20050"],
                          "source_ids": 20, "minutes": 30, "weight_kg": 82},
     "EntrySourceID 20 is AppleHealthKit, and its codes carry the source id as "
     "a prefix: 20052 is HK 52, walking. Of the 54 distinct ns20 codes in "
     "1-SourceStore, 47 strip to a valid HK case and the 7 that do not are "
     "exactly the private 209xx band."),
    ("7-codebooks/own-book-only", "a code is read only in its own book",
     "/normalize/batch", {"activities": ["1001", "1001"],
                          "source_ids": [23, 20], "minutes": 21},
     "Same digits, different issuer. Validic's 1001 is Walking; Apple has no "
     "1001, so that row stays opaque rather than borrowing a neighbour's "
     "meaning. This is the church-supper defect generalised."),
    ("7-codebooks/decoded-still-nameless", "Validic 25 decodes to 'Other'",
     "/normalize", {"activity": "25", "source_id": 23, "minutes": 30,
                    "weight_kg": 82},
     "3,308 rows. The code book resolves it perfectly -- to a word that names "
     "no activity. Decoding is not naming, so it is a placeholder, and "
     "TypeConf still records that a book was consulted."),


    # ---- 8. REAL ROWS -----------------------------------------------------
    # Every case below is one actual row from 1-SourceStore, picked by running
    # all 136,555 of them through this service. The ordinary cases are MEDIAN
    # rows of their group, deliberately -- an examples folder that showcases its
    # best row teaches nothing, and one that showcases its largest number
    # misleads. Both ends of the agreement with the device are included.
    ('8-real/apple-core-training', 'Apple HealthKit, a median real session',
     "/normalize", {'activity': '20059', 'source_id': 20, 'minutes': 44.0, 'weight_kg': 83.5},
     'A REAL ROW from WellDoc2025LLY, and a REPRESENTATIVE one: it sits at the median of its group, not at an extreme. EntrySourceID 20, code 20059 = HKWorkoutActivityType 59, core training. The device logged 100 kcal for this same bout, against our 180. Nothing was typed by hand.'),
    ('8-real/validic-walking', 'Validic, a median real walk',
     "/normalize", {'activity': '1001', 'source_id': 23, 'minutes': 30.0, 'weight_kg': 85.4},
     'A REAL ROW from WellDoc2025CVS, and a REPRESENTATIVE one: it sits at the median of its group, not at an extreme. EntrySourceID 25 = Validic_Garmin, code 1001 = Walking. The device logged 239 kcal for this same bout, against our 170. Nothing was typed by hand.'),
    ('8-real/typed-walk', "a patient's own word, median row",
     "/normalize", {'activity': 'Walk', 'minutes': 41.9, 'weight_kg': 58.9},
     "A REAL ROW from mcphases-v1, and a REPRESENTATIVE one: it sits at the median of its group, not at an extreme. mcphases-v1 exports free text; this patient's app wrote 'Walk'. The device logged 247 kcal for this same bout, against our 164. Nothing was typed by hand."),
    ('8-real/exact-agreement', 'where we and the device agree exactly',
     "/normalize", {'activity': '1001', 'source_id': 25, 'minutes': 10.0, 'weight_kg': 84.2},
     'A REAL ROW from WellDoc2025CVS. Of 26,305 rows where both numbers exist, this one lands on a ratio of 1.00. Across all of them: Spearman 0.805, median ratio 0.93, 84.3% within 2x. The device logged 56 kcal for this same bout, against our 56. Nothing was typed by hand.'),
    ('8-real/worst-disagreement', 'where we disagree with the device MOST',
     "/normalize", {'activity': '20013', 'source_id': 20, 'minutes': 131.0, 'weight_kg': 74.6},
     'A REAL ROW from WellDoc2025LLY. The honest counterweight to the case above, and it belongs in this folder. 131 minutes of cycling at MET 7.0 gives 1,197 kcal; the device says 54. One of us is wrong and this package cannot tell you which -- most likely the 131 minutes is elapsed time, not moving time. Read every estimate as an estimate. The device logged 54 kcal for this same bout, against our 1197. Nothing was typed by hand.'),
    ('8-real/no-body-mass', 'the same activity, no body mass on file',
     "/normalize", {'activity': 'Walking', 'source_id': 1, 'minutes': 60.0},
     'A REAL ROW from WellDoc2022CGM. No usable Weight row for this patient, so no dose is issued and the basis drops to per_minute. Nothing was typed by hand.'),
    ('8-real/daily-rollup', "a device's midnight roll-up",
     "/normalize", {'activity': '20903', 'source_id': 20, 'minutes': 64.0},
     'A REAL ROW from WellDoc2022CGM. Code 20903 under EntrySourceID 20. One per patient per day, at local midnight, CaloriesBurned zero. 33,617 rows look like this. Nothing was typed by hand.'),
    ('8-real/unnamed', 'the log named nothing',
     "/normalize", {'activity': 'Unknown', 'minutes': 110.0},
     "A REAL ROW from OhioT1DM. OhioT1DM records duration and nothing else; all 221 of its rows say 'Unknown'. Nothing was typed by hand."),
    ('8-real/no-codebook', 'a code with no book on this machine',
     "/normalize", {'activity': '9002', 'source_id': 24, 'minutes': 126.0, 'weight_kg': 70.3},
     "A REAL ROW from WellDoc2022CGM. Validic 9002. It IS in WellDoc's dictionary -- with a blank label. 103 rows. Nothing was typed by hand."),
    ('8-real/implausible-bout', 'a 78-hour walk',
     "/normalize", {'activity': '1001', 'source_id': 25, 'minutes': 4680.0, 'weight_kg': 60.5},
     'A REAL ROW from WellDoc2025LLY. The log claims 4,680 minutes. MET and the claimed duration are both reported; only the dose is refused, because multiplying through would make US the source of an 18,829 kcal number. The device logged 13862 kcal for this same bout. Nothing was typed by hand.'),
    ('8-real/category-word', "a real 'Sports' row",
     "/normalize", {'activity': 'Sports', 'source_id': 23, 'minutes': 18.0},
     'A REAL ROW from WellDoc2022CGM. One of 714. WEAK: the candidate rides along for a person to curate, the number does not. The device logged 82 kcal for this same bout. Nothing was typed by hand.'),
]


def post(path, payload):
    req = urllib.request.Request(URL + path, data=json.dumps(payload).encode(),
                                 headers={"Content-Type": "application/json"})
    try:
        with urllib.request.urlopen(req, timeout=120) as r:
            return r.status, json.loads(r.read())
    except urllib.error.HTTPError as e:
        return e.code, json.loads(e.read())


def write(slug, title, path, payload, why):
    d = OUT / slug
    d.mkdir(parents=True, exist_ok=True)
    status, body = post(path, payload)
    (d / "request.json").write_text(json.dumps(payload, indent=2) + "\n")
    (d / "response.json").write_text(json.dumps(body, indent=2) + "\n")
    (d / "curl.sh").write_text(
        "#!/usr/bin/env bash\n"
        "# Run from inside this folder.\n"
        f'curl -sS "${{EXNORM_URL:-{URL}}}{path}" \\\n'
        '  -H "content-type: application/json" \\\n'
        '  --data @request.json | python3 -m json.tool\n')
    (d / "NOTE.md").write_text(f"# {title}\n\nHTTP {status}\n\n{why}\n")
    return slug, title, status


def main():
    try:
        urllib.request.urlopen(URL + "/healthz", timeout=10)
    except Exception as e:
        print(f"service unreachable at {URL}: {e}")
        print("start it: Tools/plugins/haipipe-utils/skills/describe-exercise/run_server.sh")
        return 1
    lines, group = [], None
    for slug, title, path, payload, why in CASES:
        g = slug.split("/")[0]
        if g != group:
            group = g
            lines.append(f"\n## {g}\n")
        s, t, st = write(slug, title, path, payload, why)
        lines.append(f"- [`{s}`]({'api/'+s}) — {t} (HTTP {st})")
        print(f"  {st}  {s}")
    (HERE / "README.md").write_text(README_HEAD + "\n".join(lines) + "\n")
    print(f"\n{len(CASES)} cases -> {OUT}")
    return 0


if __name__ == "__main__":
    sys.exit(main())
