"""Write ref/workbench-table.md, the Insight Workbench Table, from the insight run cards (generated; never hand-edited).

    python cards_table.py            reads haipipe-insight-workflow/ref/run-cards.md, writes ../ref/workbench-table.md

One row per card, in card order, through the cards' one reader (haipipe-insight-workflow/scripts/run_cards.py), with
the columns of the table-workbench shape: Level · Space · View · Run type · Agent · Skill · Person signs · Folder. The
retired insight page keeps its table in ref/legacy/workbench-table-older.md (b11 s21 phase 2, 261008).
"""
import importlib.util
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE.parent / "ref" / "workbench-table.md"
_spec = importlib.util.spec_from_file_location(
    "run_cards", HERE.parents[1] / "haipipe-insight-workflow" / "scripts" / "run_cards.py")
RC = importlib.util.module_from_spec(_spec)
_spec.loader.exec_module(RC)
WHERE = {"Guide": "Guide › runs/", "Block": "Board › runs/", "Job": "Job › runs/", "Task": "Task › runs/",
         "Prototype": "Prototype › runs/", "Release": "Release › runs/", "Question": "Question › runs/"}


def rows() -> list[dict]:
    return [dict(c, run=RC.run_name(c)) for c in RC.cards()]


def main() -> int:
    rs = rows()
    lines = ["Insight Workbench Table", "=======================", "",
             "Generated by `../scripts/cards_table.py` from the insight run cards "
             "(`haipipe-insight-workflow/ref/run-cards.md`); never edit it by hand: change a card and run the script.",
             "Shape and check: `skills/0_utils/table-workbench/SKILL.md`. Level is the insight Board's Block, Job or Task, "
             "the Prototype's Prototype, Release or Question, or the Guide. Folder is where the Run's folder sits: a hard "
             "Run (`rNN_<partition>`) writes only its result/, a soft Run its level's own files and its passes. The "
             "retired insight page keeps `legacy/workbench-table-older.md`.", "",
             "| Level | Space | View | Run type | Agent | Skill | Person signs | Folder |",
             "|---|---|---|---|---|---|---|---|"]
    lines += [f"| {r['level']} | {r['space']} | {' · '.join(r['views']) or 'every view'} | {r["label"]} | "
              f"{r['agent']} | {r['skill']} | {r['signs']} | {WHERE[r['level']]}`{r['run']}/` |" for r in rs]
    OUT.write_text("\n".join(lines) + "\n", encoding="utf-8")
    print(f"wrote {OUT.name}: {len(rs)} rows")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
