"""Family-owned Guide bindings. Paths are relative to the plugin repository.

Working Space rosters describe the current native presenters. The Task
question interface has its own design and writer; this registry does not
create question, progress or drawing stores for an instance.
"""

TOOLKIT = "plugins/haipipe-toolkit/"
SKILLS = TOOLKIT + "skills/"


# The Insight workbench design drawing, from the served SPACE root (Guide opens it view only).
INSIGHT_DESIGN = "Tools/" + TOOLKIT + "servers/workbench-insight/studio/insight-workbench-design.excalidraw"
# The Task workbench design drawing, generated by servers/workbench-task/studio/task-workbench-design.py.
TASK_DESIGN = "Tools/" + TOOLKIT + "servers/workbench-task/studio/task-workbench-design.excalidraw"
# The Paper and Page workbench design drawings (JL 261003: "update your workbench design as
# well"): Paper's is generated by studio/paper-workbench-design.py; Page's is hand-made.
PAPER_DESIGN = "Tools/" + TOOLKIT + "servers/workbench-paper/studio/paper-workbench-design.excalidraw"
PAGE_DESIGN = "Tools/" + TOOLKIT + "servers/workbench-page/studio/page-workbench-design.excalidraw"
# The Labeling workbench UI drawing, generated by its studio/labeling-workbench-ui.py (optional plugin).
LABELING = "plugins/subjective-label/"
LABELING_SKILL = LABELING + "skills/label-building-workflow/haipipe-workbench-labeling/"
LABELING_DESIGN = "Tools/" + LABELING + "servers/workbench-labeling/studio/labeling-workbench-ui.excalidraw"


def skill(path, role):
    return {"path": SKILLS + path + "/SKILL.md", "role": role}


FAMILIES = {
    "paper": {
        "label": "Paper", "presenter": TOOLKIT + "servers/workbench-paper/paper.py",
        "table": SKILLS + "paper/haipipe-workbench-paper/ref/workbench-table.md",
        "papers_table": SKILLS + "paper/haipipe-workbench-paper/ref/paper-papers.md",
        "description": "The Paper Workbench follows one paper from idea to submission on one Board. Ideation keeps the candidate ideas and which one was admitted; Story is the paper's plan: its research questions, hypotheses and claims, the literature and study work that will support them, and the order the Sections tell it in; Sections shows every Section Page in that order with its draft, evidence and state; Delivery shows the assembled LaTeX and Word paper, its checks, the cover letter and each review round. It reads the paper's Markdown on every open and stores nothing; each run is a prompt the person copies, and each gate is closed by the person.",
        "skills": [skill("paper/haipipe-paper-workflow", "Rules, routing and release gates"),
                   skill("paper/haipipe-paper-story", "Questions, claims and supporting evidence"),
                   skill("paper/haipipe-workbench-paper", "Paper Spaces and their native sources"),
                   skill("paper/haipipe-paper-ideation", "Candidate ideas and admission"),
                   skill("paper/haipipe-paper-assemble", "Whole-paper delivery"),
                   skill("paper/haipipe-paper-round", "Review rounds and responses")],
        "method": [("Question", "Name the question, evidence needs and intended claim."),
                   ("Reason and obtain evidence", "Use existing reasoning; route missing evidence to its native owner."),
                   ("Interpret and review", "Read evidence against the claim, limits and release gates."),
                   ("Answer and revise", "Keep the supported answer and remaining issues visible.")],
        "spaces": [("Ideation", "Candidate ideas and admission"),
                   ("Story", "Spine, RoadMap Draw, Logic + Work, Related Papers"),
                   ("Sections", "Main and Appendix: table, narrative and evidence"),
                   ("Delivery", "LaTeX, Word, cover letter and review rounds: preview, artifacts and checks")],
        "folders": [("Ideation", "Paper ideation owner", "A1-Story/Story00-ideation/", "A1-Story/Story00-ideation"),
                    ("Story", "Paper Story owner", "A1-Story/Story<Letter>-<desk>-<idea>/", "A1-Story/Story[!0]*"),
                    ("Sections", "Section Page owners", "Ba-<desk>-Main/ + Bb-<desk>-Appendix/", "B[ab]-*"),
                    ("Delivery", "Assemble / Round owners", "delivery/ + Bc-<desk>-Round/", "delivery"),
                    ("Story / RoadMap Draw", "Story drawing owner", "studio/<Story stem>.excalidraw", "studio")],
        "boundary": "Guide explains the Paper family. Story, Section Pages, delivery and supporting work keep their native owners. Run completion supplies evidence; it does not resolve a question.",
        # RoadMap Draw: the workbench design drawing, generated by its studio script, view only.
        "explain": {"roadmap-draw": ("/_excalidraw/", {"board": PAPER_DESIGN}, "Workbench design", "first")},
    },
    "task": {
        "label": "Task", "presenter": TOOLKIT + "servers/workbench-task/taskboard.py",
        "table": TOOLKIT + "skills/task/haipipe-workbench-task/ref/workbench-table.md",
        "papers_table": TOOLKIT + "skills/task/haipipe-workbench-task/ref/task-papers.md",
        "description": "The Task Workbench reads one Task Block: its Jobs, Tasks and Runs, and the Questions they answer. Each Question is one main topic. Its card shows the Logic (the question, a hypothesis and what would count as the answer), the Task Work that answers it (Block → Job → Task → Run, each Run a Ticket that writes one Result with its receipt), and the Report that states the answer from exact Results. Runs and their status sit in the Runs panel; a Run, a Task Page, a report and a drawing open in one pop-out.",
        "skills": [skill("task/haipipe-task", "Block / Job / Task / Run ownership and execution"),
                   skill("page/haipipe-page-workflow", "Task Page reasoning, evidence and readings"),
                   skill("task/haipipe-workbench-task", "The Block's workbench over native records")],
        "method": [("Ask the Question", "One main topic per Question: the question, a hypothesis and what would count as the answer, signed by a person."),
                   ("Plan and review the Task", "A Task Folder holds the code, config and Ticket; a different agent reviews the code before it runs."),
                   ("Run the Ticket", "Only the Ticket writes its Result: tables, figures, drawings and a runtime receipt."),
                   ("Write the report", "Answer the Question from exact Results: Opening, Evidence, Limits and Next. Run completion does not answer it."),
                   ("Check and continue", "A different agent checks the report; a failed check routes back to the Task or report that owns it.")],
        "spaces": [("Scope", "Block · Questions · Resources: what this Block is for, the Questions it asks, and the resources they use"),
                   ("Task", "Questions: stacked cards, Logic │ Task Work │ Report · Studio: this Block's own drawings"),
                   ("Check", "Runs · Tasks · Reports: every receipt's status, each Task Folder's findings, each report's answer")],
        "folders": [("Scope / Questions", "Block owner", "board.md · Questions register", "board.md"),
                    ("Scope / Resources", "Block owner", "board.md · Related resources", "board.md"),
                    ("Task / Report", "Question Report Page owner", "reports/qNN_topic/qNN_topic.md", "reports/q[0-9][0-9]_*/*.md"),
                    ("Task / Studio", "Block drawing owner", "studio/*.excalidraw", "studio/*.excalidraw"),
                    ("Jobs", "Job owner", "jNN_<job>/src/", "j[0-9][0-9]_*/src"),
                    ("Tasks", "Task owner", "jNN_<job>/tNN_<task>/", "j[0-9][0-9]_*/t[0-9][0-9]_*"),
                    ("Run configuration", "Task owner", "<Task>/scripts/config/rNN_<run>.yaml", "j[0-9][0-9]_*/t[0-9][0-9]_*/scripts/config"),
                    ("Run records", "Task / Result owner", "<Task>/runs/ + resolved output store", "j[0-9][0-9]_*/t[0-9][0-9]_*/runs")],
        "boundary": "One Block owns this workbench: Scope, Task and Check Spaces, each with the shared Runs panel on the right. Question cards stack vertically; each opens Logic │ Task Work │ Report. Reports and working drawings live in sibling reports/ and studio/ folders. Status lives in the Runs panel and Check, never in the cards. Native Tasks and Runs retain their execution semantics; the panel copies prompts and starts nothing.",
        # RoadMap Draw: the workbench design drawing, generated from source, view only.
        "explain": {"roadmap-draw": ("/_excalidraw/", {"board": TASK_DESIGN}, "Workbench design", "first")},
    },
    "page": {
        "label": "Page", "presenter": TOOLKIT + "servers/workbench-page/outline.py",
        "table": SKILLS + "page/haipipe-workbench-page/ref/workbench-table.md",
        "papers_table": SKILLS + "page/haipipe-workbench-page/ref/page-papers.md",
        "description": "The Page Workbench works on one Page: a paper Section, a Task report, a Discovery or Insight page. Draft holds the Page's versioned plan (parts, paragraphs and Bullets, each with its role) and the prose written from it; Evidence binds every value, citation and display the plan needs to the Run Result that supports it; Delivery builds the Page as a web page, LaTeX, Word or slides and checks it. It reads the Page's Markdown and Run receipts on every open; the person approves the plan, checks sources and releases the Page.",
        "skills": [skill("page/haipipe-page-workflow", "Page planning, writing, evidence and delivery"),
                   skill("page/haipipe-workbench-page", "The Page's workbench and native lanes"),
                   skill("page/haipipe-workbench", "Storage, Surface, Writer and Boundary")],
        "method": [("Structure", "Plan coverage, Bullets, Points and evidence requirements."),
                   ("Draft and resolve evidence", "Write through the Page owner and bind typed evidence to accepted Results."),
                   ("Read and check", "Interpret sources and record owner-approved readings and checks."),
                   ("Deliver", "Produce the Page's delivery through its native writer.")],
        "spaces": [("Draft", "Structure and drafting views"), ("Evidence", "Typed evidence and supporting work"),
                   ("Delivery", "Checks and delivery artifacts")],
        "folders": [("Draft", "Page owner", "draft/", "draft"),
                    ("Evidence", "Evidence register owner", "draft/<stem>-evidence-items.md", "draft/*-evidence-items.md"),
                    ("Runs", "Page Run owner", "runs/", "runs"),
                    ("Results", "Native Result owner", "results/", "results"),
                    ("Delivery", "Page delivery owner", "delivery/", "delivery")],
        "boundary": "The Page's declared PageType and native lanes own its content and writers. Guide explains their conventions. It does not create a second Page or execution ledger.",
        # RoadMap Draw: the workbench design drawing (hand-made), view only.
        "explain": {"roadmap-draw": ("/_excalidraw/", {"board": PAGE_DESIGN}, "Workbench design", "first")},
    },
    "insight": {
        "label": "Insight", "presenter": TOOLKIT + "servers/workbench-insight/insightboard.py",
        "table": TOOLKIT + "skills/insight/haipipe-workbench-insight/ref/workbench-table.md",
        # the board page that holds Guide beside the Spaces, and where to find boards when Guide is opened alone
        "board_route": "/_board/insight-board?board={board}",
        "boards": "examples-*/*/insights/Instance-Insight-*/board.md",
        # the RoadMap's workflow: logic over data, the link between them, and the loop (JL 261003)
        "flow": {"logic": [("Question · Logic", "a question file: the ask, why now, its needs"),
                           ("Work", "its script, one run per partition"),
                           ("Report", "one page per question, a section per partition, checked")],
                 "data": [("Input · Data", "the extract, cut by one partition"),
                          ("Processing", "the power check, then run(df, ctx), then the gate"),
                          ("Output", "results/<partition>/ and reports/<partition>/")],
                 "links": ["names", "runs", "fills"],
                 "repeat": "Repeat for every partition the question is asked on, then for every question; rung by rung, "
                           "Data → Information → Knowledge → Wisdom, each rung's answers raise the next rung's questions."},
        "description": "The Insight Workbench reads one dataset and answers questions about it, from Data and Information up to Knowledge and Wisdom. Its design lives in a Prototype board: the cuts of the data, the questions and the scripts that answer them, and no data. Each extract is an Instance board read through that Prototype: one run per question and partition, and one checked page per question. The workbench shows which questions are answered on which cuts, the runs behind each answer, and what still needs a check or a signature.",
        "skills": [skill("insight/haipipe-insight", "Prototype and Instance boards, question files and partition runs"),
                   skill("insight/haipipe-insight-evidence-plan", "A question's evidence needs, agreed by a reviewer"),
                   skill("insight/haipipe-insight-check", "Question rules and each cell's status from receipts and checks"),
                   skill("page/haipipe-page-workflow", "One page per question, checked by an agent that did not write it"),
                   skill("insight/haipipe-workbench-insight", "Scope, Prototype, Insight, Check and Delivery over both boards")],
        "method": [("Design the Prototype", "Partitions, thresholds and question files with agreed needs; no data."),
                   ("Review the scripts", "Each question's script is reviewed by an agent that did not write it."),
                   ("Run each partition", "The Instance copies the scripts; one ticket per partition writes results and a generated report."),
                   ("Write and check the page", "One page per question, one section per partition; another agent's CHECK closes it."),
                   ("Change by signing", "A reviewer proposes; a person signs. A signed change retires, never edits in place.")],
        "spaces": [("Scope", "Dataset · Partitions · Questions: this board's own data: the extract, its cuts with their row counts, and the Ask box"),
                   ("Prototype", "Meta · Data · Information · Knowledge · Wisdom: the design every board of this kind reads through: the summary, partitions and shared settings, then each rung's questions with their needs, script and sign-off; RoadMap Draw holds the Prototype's own drawings"),
                   ("Insight", "One View per partition, Full to Cross: each a table of the questions, Logic / Work / Report"),
                   ("Check", "Gates · Checks · Runtime: the Instance checker's findings and every run's receipt"),
                   ("Delivery", "Handoff: signed Wisdom answers ready to leave the board")],
        "folders": [("Scope / Instance", "Instance owner", "board.md: prototype + extract", "board.md"),
                    ("Scope / Dataset and Partitions", "Prototype owner", "../Prototype-Insight-<Topic>/0-Meta/", "../Prototype-Insight-*/0-Meta/*"),
                    ("Insight / Logic", "Prototype question owners", "../Prototype-Insight-<Topic>/<rung>/<L><NN>-<name>/<L><NN>-<name>.md", "../Prototype-Insight-*/[1-4]-*/[DIKW][0-9][0-9]-*/[DIKW][0-9][0-9]-*.md"),
                    ("Insight / Work", "Instance question owners", "<rung>/<L><NN>-<name>/runs/<partition>.sh", "[1-4]-*/*/runs/*.sh"),
                    ("Insight / Report", "Run reports, generated", "<rung>/<L><NN>-<name>/reports/<partition>/report.md", "[1-4]-*/*/reports/*/report.md"),
                    ("Insight / Page", "Page owners", "<rung>/<L><NN>-<name>/<L><NN>-<name>.md", "[1-4]-*/[DIKW][0-9][0-9]-*/[DIKW][0-9][0-9]-*.md"),
                    ("Check", "Instance checker", "0-Meta/status.md, written only by the checker", "0-Meta/status.md")],
        # Method: the steps above, then the family's method cards and drawing; RoadMap Draw: the whole
        # design drawing (studio/insight-workbench-design.py), view only; Related Paper: the papers the cards cite.
        "explain": {"method": ("/_board/insight-board", {"embed": "methods", "view": "method"},
                               "Discovery methods · Design methods · Methods studio"),
                    "roadmap-draw": ("/_excalidraw/", {"board": INSIGHT_DESIGN},
                                     "Workbench design", "first"),
                    "related-paper": ("/_board/insight-board", {"embed": "methods", "view": "papers"}, "", "first")},
        "boundary": "A Prototype holds the design: partitions, question files and scripts, no data. An Instance reads one extract through one Prototype: script copies, one run per partition, and one page per question. Status is computed from run receipts and CHECK runs. Guide never signs a question change or a handoff.",
    },
    "design": {
        "label": "Design", "presenter": TOOLKIT + "servers/workbench-design/designboard.py",
        "table": TOOLKIT + "skills/design/haipipe-workbench-design/ref/workbench-table.md",
        "flow": {"logic": [("Design task · Goal", "one Design page: the task, its requirements, its one method"),
                           ("Work", "Commission, then Generate and Verify, one run per design"),
                           ("Delivery", "the designs that passed, word for word, and the csv")],
                 "data": [("Input · requirements, insights", "the Design Goal; internal insights, signed; external ones, cited"),
                          ("Processing", "Method → Generate → Evaluate, back until each design passes"),
                          ("Output", "N designs, each with its element record, in results/<run>/")],
                 "links": ["frames", "runs", "fills"],
                 "repeat": "Evaluate repeats until each design passes (the Revise loop). After a person releases them, the Exp "
                           "tests the designs in use and its data becomes the next internal insights (the Learning loop). "
                           "One page per method, so comparing methods takes one page each on the same task."},
        "skills": [skill("design/haipipe-design", "The Design family door: boards, design tasks and Design pages"),
                   skill("design/haipipe-design-goal", "The design requirements: aim, venue, rules, resources and its named elements, leave out"),
                   skill("design/haipipe-design-workflow", "Commission, Generate and Verify runs, and the records each one keeps"),
                   skill("design/haipipe-design-unit", "One Generate or Verify: the design, its element record and its checks"),
                   skill("design/haipipe-workbench-design", "Board and page surfaces; the theory of design, the method cards and their papers")],
        "method": [("Set the Design Task", "Aim · Requirements · Resources · Leave out: what every design must do and keep; a person signs."),
                   ("Pick the method", "One method per Design page, from 13 in 6 families (the board's Design Tasks views): which insights its designs may read."),
                   ("Generate N Design Items", "Each design with its element record: where each element came from, reasoned or intuitive."),
                   ("Evaluate", "Rules, fidelity, critique, pretest, by a different agent; back to Generate or Method until it passes."),
                   ("Release", "A person releases the designs that passed; Delivery holds them word for word."),
                   ("Run the Exp", "A trial in use against the control; its data becomes the next internal insights.")],
        "spaces": [("Design Tasks", "Board level. One row per Design page: its task, method, N designs and how many are ready."),
                   ("Page › Design Task", "The task once, in four views: Aim · Requirements (channel and rules) · Resources (starting text, elements) · Leave out."),
                   ("Page › Design Item", "The element matrix, then one card per design: Design · Rationale · Evaluation, runs inside."),
                   ("Page › Delivery", "Every design whose independent Verify passed, word for word, and the csv.")],
        "folders": [("Design Goal", "Design Goal owner", "design-goal.md beside board.md", "design-goal.md"),
                    ("Design Tasks", "Brief owner", "0-BR-brief/", "0-BR-brief"),
                    ("Design pages", "Design Folder owners", "2-Design/Design-NN-<audience>-<job>-<venue>/", "2-Design/Design-*"),
                    ("Design Items", "Design Folder owners", "<Design page>/draft/<stem>-design-items.md", "2-Design/Design-*/draft"),
                    ("Runs", "Design Run owners", "<Design page>/runs/", "2-Design/Design-*/runs"),
                    ("Results and element records", "Design Run owners", "<Design page>/results/<run>/ (content, checks, elements.yaml)", "2-Design/Design-*/results"),
                    ("Message theories", "Board theory owner", "design-theory.md beside board.md, when declared", "design-theory.md")],
        "description": ("The Design workbench turns a design task into designs a person can release. A board lists "
                        "its design tasks; each Design page is one task done by one design method, and it returns N "
                        "designs. Every design reads the task's requirements and, by its method, internal insights "
                        "(our own data, signed) or external ones (the literature and theory); each element of a design "
                        "records where it came from and whether it was reasoned or intuitive. An agent generates, a "
                        "different agent evaluates, a person releases, and the Exp tests the design in use."),
        # Method: the six steps, then one page (JL 261003): the theory, the method cards, the drawing
        "explain": {"method": ("/_board/design-board", {"embed": "theory", "view": "method", "views": "method"}),
                    "roadmap-draw": ("/_excalidraw/", {"board": TOOLKIT.replace("plugins/", "Tools/plugins/", 1)
                                                       + "servers/workbench-design/studio/design-workbench-ui.excalidraw"},
                                     "Workbench design", "first"),
                    # untitled, so the papers show directly under Related Paper, not in a fold (JL 261003)
                    "related-paper": ("/_board/design-board", {"embed": "theory", "view": "papers", "views": "papers"},
                                      "", "first")},
        "boundary": "Guide explains how the Design family designs: the theory, the method cards and their papers are the same on every board. Each board's Design Tasks and each Design page's goal, designs, runs and delivery keep their native owners. Commission release stays a person's decision.",
    },
    "labeling": {
        "label": "Labeling", "presenter": LABELING + "servers/workbench-labeling/labeling.py",
        "table": LABELING_SKILL + "ref/workbench-table.md",
        "papers_table": LABELING_SKILL + "ref/labeling-papers.md",
        "description": "The Labeling Workbench runs one subjective-labeling job on one Page: labels whose meaning a person must decide, such as how unsafe a reply is. Data prepares the corpus into items, holds a test set back unseen, and maps the items; Labeling is where the person confirms what each label means (G0), then labels rounds drawn from the corpus while the guideline is written down; Quality checks models against the person's held-back answers; Delivery freezes the labels and hands them on. The person is the only source of gold: a model's agreement never makes a label true. Every write goes through the job's engine, which checks the person, the gate and the held-back test on each call.",
        "skills": [{"path": LABELING_SKILL + "SKILL.md", "role": "The Page-local labeling job and its Spaces"},
                   {"path": LABELING + "skills/label-building/SKILL.md", "role": "Building the labels: meanings, rounds and guideline"},
                   {"path": LABELING + "skills/label-scanning/SKILL.md", "role": "Scanning: the final test, production and audit"}],
        "method": [("Prepare the corpus", "Turn raw conversations into checked items grouped by source, and hold a test set back by group so no source sits on both sides."),
                   ("Set up the job", "The Contract names the target, the person who decides the labels, and the custodian of the held-back test."),
                   ("Confirm the meanings", "Discuss what each label means, then the person confirms them (G0); no round is drawn before."),
                   ("Label in rounds", "Each round draws items (round 1 at random), models may pre-label them blind, and the person gives each item its final label; the guideline is revised from the judgments."),
                   ("Check against the held-back test", "Models predict the locked test; a different agent scores them against the person's blind answers, by preregistered metrics."),
                   ("Deliver", "Freeze the handoff, label the corpus with the chosen model, send risky items back to the person, audit a sample, then release the final labels.")],
        "spaces": [("Data", "Preparation · Contract · Embedding: the corpus, the job's contract, the map of items"),
                   ("Labeling", "Definition · Rounds · Guideline: what each label means, the rounds, the written guideline"),
                   ("Quality", "Test · Evaluation · Audit: the held-back test and the checks against it"),
                   ("Delivery", "Handoff · Scan · Final labels: what is frozen, scanned and released")],
        "folders": [("Labeling job", "Page-local labeling owner", "labeling/", "labeling"),
                    ("Contract", "Labeling owner", "labeling/config.yaml", "labeling/config.yaml"),
                    ("Runs", "Page-local Labeling Run owner", "runs/run-labeling-* · beside labeling/", "runs/run-labeling-*")],
        "boundary": "Guide describes the labeling family. Job-specific policies, annotations, private sources and actions stay in the native labeling surface. This family is available only when the subjective-label plugin is installed.",
        "explain": {"roadmap-draw": ("/_excalidraw/", {"board": LABELING_DESIGN}, "Workbench design", "first")},
    },
    # The Shared Workbench explains itself; it has no Board, so its folders are this server folder's files.
    "shared": {
        "label": "Shared", "presenter": TOOLKIT + "servers/workbench-shared/shared_workbench.py", "standalone": True,
        "table": TOOLKIT + "skills/page/haipipe-workbench-studio/ref/workbench-table.md",
        "papers_table": TOOLKIT + "skills/page/haipipe-workbench-studio/ref/shared-papers.md",
        "description": "The Shared Workbench is what every workbench reuses instead of owning a copy. Its Studio opens, creates and saves the Excalidraw drawings of any Page or Board, and keeps a chat and a terminal beside them; its Guide explains how each Workbench family works. It has no Board and no data of its own.",
        "skills": [skill("page/haipipe-workbench-studio", "Studio: the drawing canvas, chat and terminal every workbench reuses"),
                   skill("page/haipipe-workbench", "The Workbench contract: storage, surface, writer and boundary")],
        "method": [
            ("What is shared", "Two parts. Guide: the registry guide_families.py (one entry per family: description, method, skills, Spaces, folders, Workbench Table, papers), the presenter workbench_guide.py and the mount script guide-mount.js. Studio: the Excalidraw editor xcal.py with its proxy excalidraw_proxy.py and boot script xcal-boot.js, the chat chat.py and turnring.py, the terminal term.py, and the ✨ pens autodraw.py and autodeck.py. The host loads every workbench-* folder as one live namespace, so a family imports these by name and never copies them."),
            ("Mount Guide on a family's page", "The family's presenter calls mount_guide() with its own Space row. The Guide button goes first on that row and opens Description, Method, RoadMap Draw and Related Paper from the family's entry. Inside a Board the folder patterns resolve against that Board; on this site (/w/shared) they stay patterns."),
            ("Prepare a drawing from source", "A design drawing is written by a script beside it, studio/<name>.py, which builds the scene from the text that holds the facts (this Guide's UI drawing is studio/shared-workbench-ui.py; a paper's is studio/make_<name>.py). The .excalidraw file is generated: change the script or its source and rerun it, never the drawing. A RoadMap with a Workbench Table is drawn from that table each time Guide opens."),
            ("Follow the Studio style", "Every generated scene keeps the style in haipipe-workbench-studio/ref/draw.md: transparent boxes, one colored stroke per role, every label bound inside its box, every arrow bound at both ends, Comic Shanns, and a compact span. ✨ Draw it (autodraw.py) authors a scene from the page's own Markdown under the same rules and refuses a hand-drawn scene."),
            ("Open, create and save", "xcal.py serves a scene to the Excalidraw app through the proxy; xcal-boot.js seeds the canvas from the file, never from browser storage. A missing Page or Board scene is created empty on first open. Opening never saves: the first stroke arms the save, each save carries the revision it opened, and a stale revision shows a conflict instead of overwriting. Guide's canvases open read-only (guide=1)."),
            ("Chat and run beside the drawing", "The Studio tab stages the drawing above the chat. The chat (GUI) or the real CLI in a terminal (TUI) works on the Page or Board in view; when the person asks, the chat may redraw that page's own scene, and a kept session is saved under the page's studio/chat/."),
            ("Write the Workbench Table, then check it", "Each workbench lists its runs in ref/workbench-table.md: Space · View · Run type · Agent · Skill · Person signs. One agent writes the table and a different agent reviews it; table-workbench --check fails a missing agent or skill, and Guide draws the RoadMap from the table."),
            ("Keep ownership", "Shared parts never take over a family's content. Guide never saves; Studio writes only the scene, session or deck it was asked for, through its own route; every other write stays with the family's own skill.")],
        "explain": {"roadmap-draw": ("/_excalidraw/", {"board": TOOLKIT.replace("plugins/", "Tools/plugins/", 1)
                                                       + "servers/workbench-shared/studio/shared-workbench-ui.excalidraw"},
                                     "Workbench design", "first")},
        "spaces": [],
        "folders": [("Guide / families", "Shared Guide owner", "servers/workbench-shared/guide_families.py", "guide_families.py"),
                    ("Guide / presenter", "Shared Guide owner", "servers/workbench-shared/workbench_guide.py", "workbench_guide.py"),
                    ("Studio / draw", "Studio owner", "servers/workbench-shared/xcal.py + excalidraw_proxy.py + assets/xcal-boot.js", "xcal.py"),
                    ("Studio / chat and terminal", "Studio owner", "servers/workbench-shared/chat.py + turnring.py + term.py", "chat.py"),
                    ("Studio / ✨ pens", "Studio owner", "servers/workbench-shared/autodraw.py + autodeck.py", "autodraw.py"),
                    ("Design scenes", "Generator owner", "servers/workbench-shared/studio/*.excalidraw + *.py", "studio")],
        "boundary": "The Shared Workbench is what every family reuses. Guide explains each family and never saves; Studio opens and saves drawings and runs chat and terminal through its own routes. Each family keeps its own Spaces, content and writers.",
    },
}
