"""Family-owned Guide bindings. Paths are relative to the plugin repository.

Working Space rosters describe the current native presenters. The Task
question interface has its own design and writer; this registry does not
create question, progress or drawing stores for an instance.
"""

TOOLKIT = "plugins/haipipe-toolkit/"
SKILLS = TOOLKIT + "skills/"


def skill(path, role):
    return {"path": SKILLS + path + "/SKILL.md", "role": role}


FAMILIES = {
    "paper": {
        "label": "Paper", "presenter": TOOLKIT + "servers/workbench-paper/paper.py",
        "skills": [skill("paper/haipipe-paper-workflow", "Rules, routing and release gates"),
                   skill("paper/haipipe-paper-story", "Questions, claims and supporting evidence"),
                   skill("paper/haipipe-workbench-paper", "Paper Spaces and their native sources"),
                   skill("paper/haipipe-paper-ideation", "Candidate ideas and admission"),
                   skill("paper/haipipe-paper-assemble", "Whole-paper delivery"),
                   skill("paper/haipipe-paper-round", "Review rounds and responses")],
        "method": [("Question", "Name the question, evidence needs and intended claim."),
                   ("Reason and obtain evidence", "Use existing reasoning; route missing evidence to its native owner."),
                   ("Interpret and review", "Read evidence against the claim, limits and release gates."),
                   ("Answer and revise", "Keep the supported answer and remaining issues visible.")],
        "spaces": [("Ideation", "Candidate ideas and admission"),
                   ("Story", "Spine, RoadMap Draw, Logic + Work, Related Papers"),
                   ("Sections", "Main and Appendix: table, narrative and evidence"),
                   ("Delivery", "LaTeX, Word and review rounds")],
        "folders": [("Ideation", "Paper ideation owner", "A1-Story/Story00-ideation/", "A1-Story/Story00-ideation"),
                    ("Story", "Paper Story owner", "A1-Story/Story<Letter>-<desk>-<idea>/", "A1-Story/Story[!0]*"),
                    ("Sections", "Section Page owners", "Ba-<desk>-Main/ + Bb-<desk>-Appendix/", "B[ab]-*"),
                    ("Delivery", "Assemble / Round owners", "delivery/ + Bc-<desk>-Round/", "delivery"),
                    ("Story / RoadMap Draw", "Story drawing owner", "studio/<Story stem>.excalidraw", "studio")],
        "boundary": "Guide explains the Paper family. Story, Section Pages, delivery and supporting work keep their native owners. Run completion supplies evidence; it does not resolve a question.",
    },
    "task": {
        "label": "Task", "presenter": TOOLKIT + "servers/workbench-task/taskboard.py",
        "skills": [skill("task/haipipe-task", "Block / Job / Task / Run ownership and execution"),
                   skill("page/haipipe-page-workflow", "Task Page reasoning, evidence and readings"),
                   skill("task/haipipe-workbench-task", "The Block's workbench over native records")],
        "method": [("Question and plan", "Define what needs an answer and what would count as evidence."),
                   ("Build and execute when needed", "Native Jobs and Tasks own code, configuration, Tickets and Results."),
                   ("Read and interpret", "Relate exact Results or existing reasoning to the question."),
                   ("Report and continue", "State the answer, limits and next action. Run completion does not close a Task.")],
        "spaces": [("Task", "Task / Roadmap Studio / Related Paper / Progress Views")],
        "folders": [("Task / Questions", "Block owner", "board.md · optional Questions register", "board.md"),
                    ("Task / Report", "Question Report Page owner", "reports/qNN_topic/qNN_topic.md", "reports/q[0-9][0-9]_*/*.md"),
                    ("Roadmap Studio", "Block drawing owner", "studio/*.excalidraw", "studio/*.excalidraw"),
                    ("Related Paper", "Block reference owner", "board.md · Related Paper references", "board.md"),
                    ("Jobs", "Job owner", "jNN_<job>/src/", "j[0-9][0-9]_*/src"),
                    ("Tasks", "Task owner", "jNN_<job>/tNN_<task>/", "j[0-9][0-9]_*/t[0-9][0-9]_*"),
                    ("Run configuration", "Task owner", "<Task>/scripts/config/rNN_<run>.yaml", "j[0-9][0-9]_*/t[0-9][0-9]_*/scripts/config"),
                    ("Run records", "Task / Result owner", "<Task>/runs/ + resolved output store", "j[0-9][0-9]_*/t[0-9][0-9]_*/runs")],
        "boundary": "One Block owns this workbench. Task Space has Task, Roadmap Studio, Related Paper and Progress Views. Question cards stack vertically; each opens Logic / Work / Report columns. Reports and working drawings live in sibling reports/ and studio/ folders. Working drawings are freeform and templates are optional. Native Tasks and Runs retain their execution semantics.",
    },
    "page": {
        "label": "Page", "presenter": TOOLKIT + "servers/workbench-page/outline.py",
        "skills": [skill("page/haipipe-page-workflow", "Page planning, writing, evidence and delivery"),
                   skill("page/haipipe-workbench-page", "The Page's workbench and native lanes"),
                   skill("page/haipipe-workbench", "Storage, Surface, Writer and Boundary")],
        "method": [("Structure", "Plan coverage, Bullets, Points and evidence requirements."),
                   ("Draft and resolve evidence", "Write through the Page owner and bind typed evidence to accepted Results."),
                   ("Read and check", "Interpret sources and record owner-approved readings and checks."),
                   ("Deliver", "Produce the Page's delivery through its native writer.")],
        "spaces": [("Draft", "Structure and drafting views"), ("Evidence", "Typed evidence and supporting work"),
                   ("Delivery", "Checks and delivery artifacts")],
        "folders": [("Draft", "Page owner", "draft/", "draft"),
                    ("Evidence", "Evidence register owner", "draft/<stem>-evidence-items.md", "draft/*-evidence-items.md"),
                    ("Runs", "Page Run owner", "runs/", "runs"),
                    ("Results", "Native Result owner", "results/", "results"),
                    ("Delivery", "Page delivery owner", "delivery/", "delivery")],
        "boundary": "The Page's declared PageType and native lanes own its content and writers. Guide explains their conventions. It does not create a second Page or execution ledger.",
    },
    "insight": {
        "label": "Insight", "presenter": TOOLKIT + "servers/workbench-insight/insightboard.py",
        "skills": [skill("insight/haipipe-insight", "Dataset, DIKW questions and answering Pages"),
                   skill("insight/haipipe-workbench-insight", "Scope, Insight, Check and Delivery")],
        "method": [("Scope the inquiry", "Bind one dataset, its partitions, methods and questions."),
                   ("Answer with evidence", "Logic, Work and Report meet at the question's evidence needs."),
                   ("Check", "Read the owner-defined gates and exact native receipts."),
                   ("Handoff", "Present signed eligible answers with their sources and boundaries.")],
        "spaces": [("Scope", "Dataset, Partitions, Methods and Questions"),
                   ("Insight", "Questions by partition: Logic / Work / Report"),
                   ("Check", "Gates, Checks and Runtime"), ("Delivery", "Signed eligible answers")],
        "folders": [("Scope", "Insight Board owner", "board.md + MT00 dataset / partition sources", "board.md"),
                    ("Insight", "Question register owners", "MT01–MT04 registers", "**/MT0[1-4]*.md"),
                    ("Report", "Answering Page owners", "answering Page folders and answers.yaml", "**/answers.yaml"),
                    ("Work", "Answering Page / native Task owners", "<answering Page>/runs/ + results/", "**/runs"),
                    ("Check", "Workflow owner", "workflow/", "workflow")],
        "boundary": "One Insight Board binds one dataset. Questions, partitions, answering Pages and their native work retain their ownership. Guide never grants a signed answer or a handoff.",
    },
    "design": {
        "label": "Design", "presenter": TOOLKIT + "servers/workbench-design/designboard.py",
        "skills": [skill("design/haipipe-design", "Design goals, independent items and verification"),
                   skill("design/haipipe-workbench-design", "Board and Page design surfaces")],
        "method": [("Commission", "Bind the design task, audience, purpose, venue and acceptance."),
                   ("Generate", "The Design Folder owner produces independent design items."),
                   ("Verify", "Check each item against its own criteria and exact draft."),
                   ("Deliver", "Present currently ready items. Downstream owners decide distribution.")],
        "spaces": [("Design Tasks", "The Brief's tasks and their Design Folders"),
                   ("Theory of Design", "Theory, methods, studio and papers")],
        "folders": [("Design Tasks", "Brief owner", "0-BR-brief/", "0-BR-brief"),
                    ("Design Folders", "Design Folder owners", "2-Design/Design-NN-<audience>-<job>-<venue>/", "2-Design/Design-*"),
                    ("Theory", "Family / Board theory owners", "design-theory.md beside board.md, when declared", "design-theory.md"),
                    ("Runs", "Design Folder owners", "<Design Folder>/runs/", "2-Design/Design-*/runs")],
        "boundary": "The Board coordinates tasks and theory. Each Design Folder owns items, runs and delivery. Readiness and distribution remain decisions of their native owners.",
    },
    "labeling": {
        "label": "Labeling", "presenter": "plugins/subjective-label/servers/workbench-labeling/labeling.py",
        "skills": [{"path": "plugins/subjective-label/skills/label-building-workflow/haipipe-workbench-labeling/SKILL.md",
                    "role": "The Page-local labeling job and its Spaces"}],
        "method": [("Data and contract", "Read the native job's data scope and declared labeling contract."),
                   ("Label", "Use the labeling owner's current rounds and guidelines."),
                   ("Quality", "Read checks and review disagreements through the native workflow."),
                   ("Deliver", "Present the owner's accepted labeling outputs.")],
        "spaces": [("Data", "The job's input and data scope"), ("Labeling", "Definition, rounds and guidelines"),
                   ("Quality", "Checks and review"), ("Delivery", "Accepted job outputs")],
        "folders": [("Labeling job", "Page-local labeling owner", "labeling/", "labeling"),
                    ("Contract", "Labeling owner", "labeling/config.yaml", "labeling/config.yaml"),
                    ("Runs", "Page-local Labeling Run owner", "runs/run-labeling-* · beside labeling/", "runs/run-labeling-*")],
        "boundary": "Guide describes the labeling family. Job-specific policies, annotations, private sources and actions stay in the native labeling surface. This family is available only when the subjective-label plugin is installed.",
    },
}
