#!/bin/bash
# =============================================================================
# Template for runs/<NAME>.sh
# =============================================================================
# Each run.sh is a thin wrapper that:
#   1. Snapshots launch state -> results/<NAME>/runtime.yaml (status: running)
#   2. Convert .py -> template .ipynb
#   3. papermill execute -> notebooks/<NAME>.ipynb
#   4. Finalize runtime.yaml (status: ok | failed)
#
# Notebook policy (configs/<RUN>.yaml -> _meta.notebook: full | thin | off):
#   full (default) keep the executed notebook with all outputs
#   thin           execute, then clear cell outputs (small record; keeps code+params,
#                  drops bulky stream/image output) — good for heavy compute (training/data)
#   off            execute via papermill (so config injection + the .py run identically),
#                  but DON'T keep the .ipynb artifact at all
# All three execute the .py the same way; they differ only in what notebook is retained.
#
# Variables you MUST set:
#   TASK_NAME — the .py basename (without .py) at task root
#
# Everything else is derived from $0 (the script path).
# =============================================================================

set -uo pipefail

# ─── Manual config: edit for the task ──────────────────────────────────────
TASK_NAME="01_pretrain_baseline"          # the <task>.py at task root

# ─── 1. Resolve identity from $0 ───────────────────────────────────────────
RUN_NAME="$(basename "$0" .sh)"                            # e.g. run_seed42_baseline
TASK_DIR="$(cd "$(dirname "$0")/.." && pwd)"                # absolute task-folder path
REPO_ROOT="$(git -C "$TASK_DIR" rev-parse --show-toplevel)"
STARTED="$(date -Iseconds)"                                # 2026-05-24T14:30:01-04:00

CONFIG="configs/${RUN_NAME}.yaml"

# ─── 1a. Resolve the OUTPUT ROOT: am I serving a consumer, or myself? ───────
# A task-folder is SHARED CODE; a run of it is one CALL (JL 260821). When the
# call serves a consumer that owns its own store — an InsightBoard, say — the
# generated bytes belong to that store, mirrored under the task's path, so the
# same code answers the same question on a second cohort without being copied.
# With no store declared, output stays task-local and nothing changes.
#
#   RESULT_STORE env       one caller overriding one run          (wins)
#   config `store:` key    a standing declaration for this call
#   neither                task-local $TASK_DIR                   (the default)
#
# The task layer is told a PATH, never a consumer identity: a dispatching probe
# supplies the store, and the executor still cannot learn whose claim it serves.
STORE="${RESULT_STORE:-$(sed -n 's/^store:[[:space:]]*//p' "$TASK_DIR/$CONFIG" 2>/dev/null | head -1)}"
if [ -n "$STORE" ]; then
  case "$STORE" in /*) : ;; *) STORE="$REPO_ROOT/$STORE" ;; esac   # repo-relative allowed
  case "$TASK_DIR" in
    */tasks/*) TASK_REL="${TASK_DIR#*/tasks/}" ;;   # mirror the task tree in the store
    *) echo "==> BLOCKED: a store is declared but $TASK_DIR is not under a tasks/" >&2
       echo "    directory, so there is no path to mirror. Move the task-folder" >&2
       echo "    under tasks/, or drop the store: key to run self-serving." >&2
       exit 2 ;;
  esac
  OUTPUT_ROOT="$STORE/$TASK_REL"
else
  OUTPUT_ROOT="$TASK_DIR"
  # SPLIT-BANK GUARD (JL 260823). Writing task-local is normal — unless some
  # store already holds answers for THIS task-folder, which means the folder is
  # serving a consumer and this run was launched without being told. Two banks
  # for one folder is the failure the store mechanism exists to prevent: the
  # qa gate scans one of them, so the other's answers are invisible and the
  # same work gets commissioned twice.
  if [ -n "${RESULT_STORE_SEARCH_ROOT:-$REPO_ROOT/_WorkSpace}" ] && [ -d "${RESULT_STORE_SEARCH_ROOT:-$REPO_ROOT/_WorkSpace}" ]; then
    _rel="${TASK_DIR#*/tasks/}"
    _hits=$(find "${RESULT_STORE_SEARCH_ROOT:-$REPO_ROOT/_WorkSpace}" -type d -path "*/${_rel}/QA" 2>/dev/null | head -3)
    if [ -n "$_hits" ]; then
      echo "==> [warn] SPLIT BANK: this run writes task-local, but a store already" >&2
      echo "    holds a QA bank for ${_rel}:" >&2
      echo "$_hits" | sed 's/^/      /' >&2
      echo "    Declare store: in configs/${RUN_NAME}.yaml, or export RESULT_STORE," >&2
      echo "    unless serving no consumer is genuinely what you want here." >&2
    fi
    unset _rel _hits
  fi
fi
export OUTPUT_ROOT

RESULTS_DIR="$OUTPUT_ROOT/results/${RUN_NAME}"
RUNTIME_YAML="$RESULTS_DIR/runtime.yaml"
NOTEBOOK_TEMPLATE="$OUTPUT_ROOT/notebooks/_source.ipynb"
NOTEBOOK_OUT="$OUTPUT_ROOT/notebooks/${RUN_NAME}.ipynb"

# The .py reads this and must never build an output path of its own.
export RESULT_DIR="$RESULTS_DIR"

# Notebook policy: full (keep) | thin (keep, outputs cleared) | off (execute, don't keep).
NOTEBOOK_MODE="$(grep -E '^\s*notebook:\s*(full|thin|off)\b' "$TASK_DIR/$CONFIG" 2>/dev/null | awk '{print $2}' | head -1)"
NOTEBOOK_MODE="${NOTEBOOK_MODE:-full}"
NOTEBOOK_RECORD=$([ "$NOTEBOOK_MODE" = "off" ] && echo "(off)" || echo "$NOTEBOOK_OUT")

mkdir -p "$RESULTS_DIR" "$OUTPUT_ROOT/notebooks"

# ─── 2. Capture launch state ───────────────────────────────────────────────
GIT_SHA="$(git -C "$TASK_DIR" rev-parse --short HEAD 2>/dev/null || echo unknown)"
HOST="$(hostname)/$(whoami)"
CMD="bash $(realpath "$0")"

# ─── 2a. Pre-flight code review gate ───────────────────────────────────────
# Block launch unless a fresh CODE_REVIEW.md (produced by the haipipe-task-reviewer-agent (Gate 1)
# agent) exists for this task-folder and matches the current git_sha.
# Skip mechanisms (any one):
#   • _meta.skip_review: true   in configs/<RUN_NAME>.yaml
#   • HAIPIPE_SKIP_REVIEW=1     env var at launch
# Verdict semantics:
#   pass | skipped → proceed
#   warn           → proceed with stderr warning
#   fail | <none>  → exit 2; user must run the agent or fix code
CODE_REVIEW="$TASK_DIR/CODE_REVIEW.md"   # reviews CODE at a git_sha, so it stays with
                                        # the code in BOTH modes. Only RUN_AUDIT.md,
                                        # which audits one run's results, follows output.
SKIP_REVIEW_CONFIG="$(grep -E '^\s*skip_review:\s*true\b' "$TASK_DIR/$CONFIG" 2>/dev/null || true)"
if [ -n "$SKIP_REVIEW_CONFIG" ] || [ "${HAIPIPE_SKIP_REVIEW:-0}" = "1" ]; then
  echo "==> [pre-flight] code review SKIPPED (explicit skip flag)" >&2
else
  if [ ! -f "$CODE_REVIEW" ]; then
    echo "==> [pre-flight] BLOCKED: no CODE_REVIEW.md in $TASK_DIR" >&2
    echo "    Run the Task Reviewer agent (GATE 1) on this task-folder first," >&2
    echo "    or set HAIPIPE_SKIP_REVIEW=1 to bypass." >&2
    echo "    Agent: Tools/plugins/haipipe-toolkit/skills/task/agents/haipipe-task-reviewer-agent.md" >&2
    exit 2
  fi
  REVIEW_SHA="$(grep -E '^- git_sha:' "$CODE_REVIEW" 2>/dev/null | awk '{print $3}')"
  REVIEW_VERDICT="$(grep -E '^- overall_verdict:' "$CODE_REVIEW" 2>/dev/null | awk '{print $3}')"
  if [ "$REVIEW_SHA" != "$GIT_SHA" ] && [ "$GIT_SHA" != "unknown" ]; then
    echo "==> [pre-flight] BLOCKED: CODE_REVIEW.md is stale" >&2
    echo "    review git_sha = ${REVIEW_SHA:-<none>}, current git_sha = $GIT_SHA" >&2
    echo "    Re-run the Task Reviewer agent (GATE 1), or set HAIPIPE_SKIP_REVIEW=1." >&2
    exit 2
  fi
  case "$REVIEW_VERDICT" in
    pass|skipped)
      echo "==> [pre-flight] code review verdict=$REVIEW_VERDICT (proceeding)" >&2
      ;;
    warn)
      echo "==> [pre-flight] code review verdict=WARN (proceeding — see $CODE_REVIEW)" >&2
      ;;
    fail)
      echo "==> [pre-flight] BLOCKED: code review verdict=FAIL" >&2
      echo "    See $CODE_REVIEW for action items." >&2
      echo "    Fix and re-run the agent, or set HAIPIPE_SKIP_REVIEW=1 to override." >&2
      exit 2
      ;;
    *)
      echo "==> [pre-flight] BLOCKED: CODE_REVIEW.md has unrecognized verdict='$REVIEW_VERDICT'" >&2
      echo "    Expected one of: pass | warn | fail | skipped" >&2
      exit 2
      ;;
  esac
fi

# ─── 3. Write runtime.yaml (status: running, atomic) ───────────────────────
cat > "$RUNTIME_YAML.tmp" <<EOF
status:     running
started:    $STARTED
git_sha:    $GIT_SHA
host:       $HOST
cmd:        $CMD
config:     $CONFIG
notebook:   $NOTEBOOK_RECORD
EOF
mv "$RUNTIME_YAML.tmp" "$RUNTIME_YAML"

# ─── 4. Execute (convert + papermill, per notebook policy) ─────────────────
# off → execute to a temp notebook we delete after; full/thin → keep the real one.
if [ "$NOTEBOOK_MODE" = "off" ]; then
  NB_TARGET="$OUTPUT_ROOT/notebooks/.${RUN_NAME}.tmp.ipynb"
else
  NB_TARGET="$NOTEBOOK_OUT"
fi

EXIT_CODE=0
{
  python "$REPO_ROOT/code/scripts/convert_to_notebooks.py" \
         "$TASK_DIR/${TASK_NAME}.py" \
         -o "$NOTEBOOK_TEMPLATE"

  papermill "$NOTEBOOK_TEMPLATE" "$NB_TARGET" \
            -p config "$TASK_DIR/$CONFIG"
} || EXIT_CODE=$?

# Apply notebook policy (does not affect EXIT_CODE — the run already happened).
case "$NOTEBOOK_MODE" in
  thin) jupyter nbconvert --clear-output --inplace "$NB_TARGET" 2>/dev/null \
          || echo "==> [warn] notebook=thin: clear-output failed; keeping full notebook" >&2 ;;
  off)  rm -f "$NB_TARGET" ;;
esac

# ─── 5. Finalize runtime.yaml ──────────────────────────────────────────────
ENDED="$(date -Iseconds)"
DURATION="$(python3 -c "
from datetime import datetime
s = datetime.fromisoformat('$STARTED'); e = datetime.fromisoformat('$ENDED')
d = e - s; m, s = divmod(int(d.total_seconds()), 60); h, m = divmod(m, 60)
print(f'{h}h{m:02d}m' if h else f'{m}m{s:02d}s')
")"
STATUS=$([ $EXIT_CODE -eq 0 ] && echo ok || echo failed)
HEADLINE="$(python3 -c "
import json
try:
    d = json.load(open('$RESULTS_DIR/metrics.json'))
    print(d.get('summary', {}).get('headline') or '-')
except Exception:
    print('-')
")"

cat > "$RUNTIME_YAML.tmp" <<EOF
status:     $STATUS
started:    $STARTED
ended:      $ENDED
duration:   $DURATION
git_sha:    $GIT_SHA
host:       $HOST
exit_code:  $EXIT_CODE
cmd:        $CMD
config:     $CONFIG
notebook:   $NOTEBOOK_RECORD
headline:   $HEADLINE
EOF
mv "$RUNTIME_YAML.tmp" "$RUNTIME_YAML"

# ─── 6. Hand off observability to Report stage ─────────────────────────────
echo "==> Runtime written to $RUNTIME_YAML"
echo "==> Next: /haipipe-task report $TASK_DIR"

exit $EXIT_CODE
