#!/usr/bin/env python3
"""Regenerate every task page and every sbatch README from the tree.

    python3 _tools/write_pages.py [block ...]        default: every b* block

A page that LISTS what the tree already holds drifts the moment anything is
renamed, and every rename in this project so far left one pointing at a name
that no longer exists. So the listing half is generated, never typed. Only the
head of a task page -- its title and the one sentence saying what the cohort is
-- is hand-written, and it is preserved verbatim across regenerations.

Checker code S8 is the other half: it fails when any page names a folder,
ticket or script that does not exist, so a page left unregenerated is caught.
"""
import pathlib, re, sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
MARK = "<!-- Generated by _tools/write_pages.py. Everything below is read off the tree; edit above it. -->"

def natural(p): return [int(x) if x.isdigit() else x for x in re.split(r'(\d+)', p.name)]

def psd1(sb):
    f = sb / "batch.psd1"
    if not f.is_file(): return None
    d = dict(re.findall(r"^\s*(Mode|Ceiling|CollisionKey|Why)\s*=\s*'?([^'\n]+?)'?\s*$", f.read_text(), re.M))
    return d or None

def task_page(block, job, task):
    addr = block.name[:3] + job.name[:3] + task.name[:3]
    own  = sorted(f.name for f in task.iterdir() if f.is_file() and f.suffix in (".do", ".py"))
    cfgd = task / "config"
    runcfg = sorted([c for c in cfgd.glob("*.do") if re.match(r'^r\d\d_', c.name)], key=natural) if cfgd.is_dir() else []
    shared = sorted([c.name for c in cfgd.glob("*.do") if not re.match(r'^r\d\d_', c.name)]) if cfgd.is_dir() else []
    tickets = sorted((task / "runs").rglob("*.ps1"), key=natural) if (task / "runs").is_dir() else []
    sb = job / "sbatch"
    d = psd1(sb)

    L = [MARK, "", "## Opening", "",
         f"- **block** `{block.name}` · **job** `{job.name}`",
         f"- **address** `{addr}`",
         f"- **its own files** " + (", ".join(f"`{o}`" for o in own) if own else "none"),
         f"- **shared code** `../src/` — {len(list((job/'src').rglob('*.do')))} .do files, shared with every task in this job",
         f"- **shared config** " + (", ".join(f"`config/{s}`" for s in shared) if shared else "none")
           + f" · **run configs** {len(runcfg)} · **tickets** {len(tickets)}", ""]

    L += ["## How to run", "", "```powershell"]
    if tickets:
        rel = tickets[0].relative_to(job)
        L += ["# one run: a ticket names the config beside it and nothing else",
              "." + "\\" + str(rel).replace("/", "\\")]
    entry = sb / "by_task" / f"{task.name}.ps1"
    L += ["", "# every run of this task, and nothing else"]
    if entry.is_file():
        L += [f".\\sbatch\\by_task\\{task.name}.ps1 -WhatIf"]
    else:
        L += [f".\\sbatch\\run_slice.ps1 -Task {task.name} -WhatIf"]
    if d:
        L += ["", f"# that batch runs {'ONE AT A TIME' if d['Mode']=='sequential' else d['Ceiling'] + ' AT A TIME'}"
                  f" — see sbatch/batch.psd1"]
    L += ["```", "",
          "> Design build. Not executed: this machine has no Stata and no CMS stores."]
    return "\n".join(L) + "\n"

def sbatch_readme(job):
    sb = job / "sbatch"
    d  = psd1(sb)
    tickets = sorted(job.glob("t*/runs/**/*.ps1"))
    axes = sorted(p for p in sb.iterdir() if p.is_dir() and p.name.startswith("by_"))
    L = [f"# {job.name} · sbatch", "", MARK, "",
         "## One by one, or several at once", ""]
    if not d:
        L += ["**Not declared.** `run_slice.ps1` refuses to start until `batch.psd1` says so.", ""]
    else:
        mode = "ONE AT A TIME (sequential)" if d["Mode"] == "sequential" else f"{d['Ceiling']} AT A TIME (parallel)"
        L += [f"- **{mode}** — declared in `batch.psd1`, printed before every batch, enforced by `run_slice.ps1`",
              f"- **never together** — two runs equal on **{d['CollisionKey'].replace(',', ' + ')}** write the same files,",
              f"  so they land in different waves however wide the job runs",
              f"- **why** — {d['Why']}",
              f"- **override** — `-Sequential` forces one at a time; `-Parallel <N>` widens it, never past the ceiling of {d['Ceiling']}",
              ""]
    L += ["## There is no run-everything list, on purpose", "",
          "A file naming every ticket only restates what `t*/runs/` already says, and then",
          "has to be kept in step with it. The tree IS the list: `run_slice.ps1` with no",
          "filter runs everything, and `-WhatIf` prints the plan, wave by wave, computed",
          "from disk so it can never be stale.", "",
          "```powershell",
          ".\\run_slice.ps1 -WhatIf          # the plan, wave by wave",
          ".\\run_slice.ps1                  # run it",
          ".\\run_slice.ps1 -Sequential      # same runs, one at a time",
          "```", "",
          f"## Files ({len(tickets)} tickets across {len(sorted(job.glob('t*/')))} task(s))", "",
          "- `run_slice.ps1` — the engine. Reads each ticket's coordinates from its own name.",
          "- `batch.psd1` — this job's answer to one-by-one or parallel, and why.",
          ]
    for a in axes:
        n = len(list(a.glob("*.ps1")))
        L += [f"- `{a.name}/` — {n} named entry point(s) for one axis, numbered in project order"]
    L += ["", "They compose, because every entry forwards what it is given:", "",
          "```powershell",
          f".\\{axes[0].name}\\<name>.ps1 -WhatIf -Parallel 1" if axes else ".\\run_slice.ps1 -WhatIf",
          "```"]
    return "\n".join(L) + "\n"


# --- the named entry points -------------------------------------------------
# One per distinct value of each axis the tickets actually carry, so the folder
# can never offer a slice that no longer exists. Order is PROJECT order, which
# is derivable: the order the values first appear as you walk r01, r02, r03...
COORD = [
    (re.compile(r'^r\d\d_D_reg_.+?_(?P<Trait>[a-z]+)_(?P<Window>af\d+d|allw)_(?P<Family>.+)$'), None),
    (re.compile(r'^r\d\d_C_data_.+?_(?P<y0>\d{4})_(?P<y1>\d{4})$'), "Window"),
    (re.compile(r'^r\d\d_.*?(?P<Year>\d{4})_(?P<Source>full|synth)$'), None),
    (re.compile(r'^r\d\d_D_reg_.+?_(?P<Analysis>[a-z]+)$'), None),
]
ENTRY = """# Every run in {job} with {axis} = {value}.
# Filters compose. Every other axis, and the run controls, are forwarded as NAMED
# parameters: $PSBoundParameters is a hashtable, so `-WhatIf` stays `-WhatIf`.
# An array splat (@Rest) passes its items POSITIONALLY, which silently bound
# `-WhatIf` to `-Family` and made every one of these files fail.
#   .\\by_{axis_l}\\{stem}.ps1 -WhatIf
#   .\\by_{axis_l}\\{stem}.ps1 -Sequential      one at a time, whatever batch.psd1 says
param(
{params}
    [switch]$Sequential, [int]$Parallel = 0, [switch]$ContinueOnError, [switch]$WhatIf
)
$SB = $PSScriptRoot
while ($SB -and (Split-Path -Leaf $SB) -ne "sbatch") {{ $SB = Split-Path -Parent $SB }}
& "$SB\\run_slice.ps1" -{axis} {value} @PSBoundParameters
exit $LASTEXITCODE
"""
AXES = ["Task","Family","Window","Trait","Analysis","Year","Source"]

def coords(name, task):
    o = {"Task": task}
    for rx, joined in COORD:
        m = rx.match(name)
        if not m: continue
        g = m.groupdict()
        if joined == "Window": o["Window"] = f"{g['y0']}_{g['y1']}"
        else: o.update({k: v for k, v in g.items() if v is not None})
        return o
    return o

def entrypoints(job):
    sb = job / "sbatch"
    if not sb.is_dir(): return 0
    rows = []
    for tk in sorted(job.glob("t*/runs/**/*.ps1")):
        task = tk.parent
        while task.name != "runs": task = task.parent
        rows.append(coords(tk.stem, task.parent.name))
    order = {}
    for r in rows:
        for k, v in r.items(): order.setdefault(k, []) and None
        for k, v in r.items():
            order.setdefault(k, [])
            if v not in order[k]: order[k].append(v)

    for d in [p for p in sb.iterdir() if p.is_dir() and p.name.startswith("by_")]:
        for old in d.glob("*.ps1"): old.unlink()
    n = 0
    for axis, values in order.items():
        d = sb / f"by_{axis.lower()}"
        if len(values) < 2:
            if d.is_dir() and not any(d.iterdir()): d.rmdir()
            continue
        d.mkdir(exist_ok=True)
        for i, v in enumerate(values, 1):
            stem = v if axis == "Task" else f"{i:02d}_{v}"
            others = [a for a in AXES if a != axis]
            params = "    " + ", ".join(f"[string[]]${a}" for a in others) + ","
            (d / f"{stem}.ps1").write_text(ENTRY.format(
                job=job.name, axis=axis, axis_l=axis.lower(), value=v, stem=stem, params=params))
            n += 1
    for d in [p for p in sb.iterdir() if p.is_dir() and p.name.startswith("by_")]:
        if not any(d.iterdir()): d.rmdir()
    return n

def main():
    names = sys.argv[1:] or [p.name for p in sorted(ROOT.glob("b*")) if p.is_dir()]
    n_t = n_s = n_e = 0
    for bn in names:
        block = ROOT / bn
        for job in sorted(p for p in block.iterdir() if p.is_dir() and p.name.startswith("j")):
            for task in sorted(p for p in job.iterdir() if p.is_dir() and re.match(r'^t\d\d_', p.name)):
                page = task / f"{task.name}.md"
                head = ""
                if page.is_file():
                    txt = page.read_text()
                    head = txt.split(MARK)[0] if MARK in txt else txt.split("## Opening")[0]
                if not head.strip():
                    head = f"# {task.name}\n\nTODO: one sentence saying what this task is.\n\n"
                page.write_text(head.rstrip() + "\n\n" + task_page(block, job, task))
                n_t += 1
            if (job / "sbatch").is_dir():
                n_e += entrypoints(job)
                (job / "sbatch" / "README.md").write_text(sbatch_readme(job)); n_s += 1
    print(f"wrote {n_t} task page(s), {n_e} named entry point(s), {n_s} sbatch README(s)")

if __name__ == "__main__":
    main()
