"""Generate the two diagram files that list code, so they cannot drift from it (never edit their output):

    10-ui-elements.txt   every view (web/src/views.ts: icon, label, rail group, the DATA views' banner), then every
                         component and module in web/src/ with the first paragraph of its opening comment
    11-routes.txt        every route the FastAPI app mounts (main.app.routes): method, path, the router module and
                         the first paragraph of the handler's docstring

    python diagram/build_ui_docs.py          (from haichat-inlab/, or anywhere: paths are found from this file)
"""
from __future__ import annotations

import inspect
import os
import re
import sys
import textwrap
from pathlib import Path

HERE = Path(__file__).resolve().parent
APP = HERE.parent
SRC = APP / "web" / "src"
WIDTH = 100
HEAD = "generated by diagram/build_ui_docs.py from the code; do not edit (rerun it)"


def opening_comment(path: Path) -> str:
    """The first paragraph of a file's opening /* … */ or // comment, as plain text."""
    text = path.read_text(encoding="utf-8")
    m = re.match(r"\s*/\*+(.*?)\*/", text, re.S)
    if m:
        lines = [re.sub(r"^\s*\*\s?", "", l) for l in m.group(1).splitlines()]
    else:
        lines = [l.strip()[2:].strip() for l in text.splitlines() if l.strip().startswith("//")][:12]
    paras, para = [], []
    for l in lines + [""]:
        if not l.strip():
            if para:
                paras.append(" ".join(para))
                para = []
            continue
        para.append(l.strip())
    # the first paragraph; when it is only the element's name and title, the next one too
    out = paras[0] if paras else ""
    if len(out) < 90 and len(paras) > 1:
        out += " " + paras[1]
    return re.sub(r"\s+", " ", out).strip()


def views() -> list[tuple[str, str, str, str]]:
    ts = (SRC / "views.ts").read_text(encoding="utf-8")
    meta = re.findall(r"(\w+):\s*\{icon:\s*'([^']*)',\s*label:\s*'([^']*)',\s*group:\s*'(\w+)'\}", ts)
    return [(key, icon, label, group) for key, icon, label, group in meta]


def blurbs() -> dict[str, tuple[str, str]]:
    ts = (SRC / "views.ts").read_text(encoding="utf-8")
    block = ts.split("LAYER_BLURB", 1)[1].split("};", 1)[0]
    out = {}
    for key, store, what in re.findall(r"(\w+):\s*\{\s*store:\s*'([^']*)',\s*what:\s*'((?:[^'\\]|\\.)*)',?\s*\}",
                                       block, re.S):
        out[key] = (store, what.replace("\\'", "'"))
    return out


def placeholders() -> dict[str, list[str]]:
    """{view: [the scopes where it is only a placeholder, so hidden]} from views.ts PLACEHOLDER."""
    ts = (SRC / "views.ts").read_text(encoding="utf-8")
    block = ts.split("PLACEHOLDER", 1)[1].split("};", 1)[0]
    return {k: re.findall(r"'(\w+)'", v) for k, v in re.findall(r"(\w+):\s*\[([^\]]*)\]", block)}


def ui_elements() -> str:
    out = ["🧩  UI elements — every view, then every component", "═" * 67, "", f"({HEAD})", "",
           "─§ The views (web/src/views.ts) " + "─" * 35, ""]
    bl = blurbs()
    hidden = placeholders()
    for key, icon, label, group in views():
        line = f"  {icon} {label:<10} {group:<8} view '{key}'"
        if hidden.get(key):
            line += "   hidden at " + " · ".join(hidden[key]) + " (a placeholder there)"
        out.append(line)
        if key in bl:
            store, what = bl[key]
            out += textwrap.wrap(f"{store}: {what}", WIDTH, initial_indent=" " * 6, subsequent_indent=" " * 6)
    out += ["", "─§ The components (web/src/components/) " + "─" * 27, ""]
    for f in sorted((SRC / "components").iterdir()):
        if f.suffix in (".tsx", ".ts"):
            out.append(f"  {f.name}")
            out += textwrap.wrap(opening_comment(f) or "(no opening comment)", WIDTH,
                                 initial_indent=" " * 6, subsequent_indent=" " * 6)
            out.append("")
    out += ["─§ The shell and state (web/src/) " + "─" * 34, ""]
    for f in sorted(SRC.iterdir()):
        if f.is_file() and f.suffix in (".tsx", ".ts") and f.name not in ("index.ts",):
            out.append(f"  {f.name}")
            out += textwrap.wrap(opening_comment(f) or "(no opening comment)", WIDTH,
                                 initial_indent=" " * 6, subsequent_indent=" " * 6)
            out.append("")
    out += ["     see 05-frontend-shell.txt  →  how the rail, the dock and the one reducer fit", ""]
    return "\n".join(out)


def routes() -> str:
    sys.path.insert(0, str(APP))
    os.chdir(APP)
    import main  # noqa: E402  — builds the app; the stores need not be mounted to list its routes

    rows = []
    for r in main.app.routes:
        path = getattr(r, "path", "")
        if path.startswith(("/docs", "/redoc", "/openapi")):
            continue
        ep = getattr(r, "endpoint", None)
        methods = sorted(getattr(r, "methods", None) or (["WS"] if "websocket" in type(r).__name__.lower() else ["-"]))
        methods = [m for m in methods if m != "HEAD"] or ["GET"]
        module = getattr(ep, "__module__", "") if ep else ""
        doc = " ".join((inspect.getdoc(ep) or "").split("\n\n")[0].split()) if ep else ""
        if type(r).__name__ == "Mount":
            module, doc = "main", "the built SPA (web/dist), served at /"
        rows.append((" ".join(methods), path, module, doc))
    out = ["🔌  Routes — every route the app mounts", "═" * 67, "", f"({HEAD})", "",
           f"  {len(rows)} routes from main.app.routes, grouped by the module that owns them", ""]
    for module in sorted({m for _, _, m, _ in rows}):
        out.append(f"─§ {module} " + "─" * max(4, 64 - len(module)))
        out.append("")
        for method, path, mod, doc in rows:
            if mod == module:
                out.append(f"  {method:<6} {path}")
                if doc:
                    out += textwrap.wrap(doc, WIDTH, initial_indent=" " * 9, subsequent_indent=" " * 9)
        out.append("")
    out += ["     see 04-backend-api.txt  →  which store each router reads", ""]
    return "\n".join(out)


def main_() -> None:
    (HERE / "10-ui-elements.txt").write_text(ui_elements(), encoding="utf-8")
    (HERE / "11-routes.txt").write_text(routes(), encoding="utf-8")
    print("wrote diagram/10-ui-elements.txt and diagram/11-routes.txt")


if __name__ == "__main__":
    main_()
